const localeOrder = ['en', 'zh', 'es', 'ja', 'fr', 'de', 'pt', 'ko', 'it'];

const localized = (...values) => Object.fromEntries(localeOrder.map((locale, index) => [locale, values[index]]));

export const badgeGuideSource = {
  wiki: 'https://peak.wiki.gg/wiki/Badges?oldid=10228',
  category: 'https://peak.wiki.gg/wiki/Category:Badges',
  license: 'https://creativecommons.org/licenses/by-sa/4.0/',
  store: 'https://store.steampowered.com/app/3527290/PEAK/',
  patch203: 'https://store.steampowered.com/news/app/3527290/view/1842212951300914',
  patch204: 'https://store.steampowered.com/news/app/3527290/view/1842846814441503',
  published: '2026-09-10',
  snapshot: '2026-08-13',
};

export const badgeGuideEntries = [
  {
    group: 'route',
    name: 'Alpinist Badge',
    condition: localized(
      'Climb past ALPINE.',
      '爬过 ALPINE。',
      'Supera ALPINE.',
      'ALPINE を越えて登る。',
      'Franchir ALPINE en grimpant.',
      'ALPINE überklettern.',
      'Suba além de ALPINE.',
      'ALPINE을 지나 등반하세요.',
      'Supera ALPINE arrampicandoti.',
    ),
    grantKey: 'campfireLiving',
    reward: 'Aviator Hat + Aviator Outfit',
  },
  {
    group: 'route',
    name: 'Forestry Badge',
    condition: localized(
      'Climb past ROOTS.',
      '爬过 ROOTS。',
      'Supera ROOTS.',
      'ROOTS を越えて登る。',
      'Franchir ROOTS en grimpant.',
      'ROOTS überklettern.',
      'Suba além de ROOTS.',
      'ROOTS를 지나 등반하세요.',
      'Supera ROOTS arrampicandoti.',
    ),
    grantKey: 'campfireLiving',
    reward: 'Gnome Hat + Gnome Outfit',
  },
  {
    group: 'route',
    name: 'Beachcomber Badge',
    condition: localized(
      'Climb past SHORE.',
      '爬过 SHORE。',
      'Supera SHORE.',
      'SHORE を越えて登る。',
      'Franchir SHORE en grimpant.',
      'SHORE überklettern.',
      'Suba além de SHORE.',
      'SHORE를 지나 등반하세요.',
      'Supera SHORE arrampicandoti.',
    ),
    grantKey: 'campfireLiving',
    reward: 'Straw Hat',
  },
  {
    group: 'survival',
    name: 'Endurance Badge',
    condition: localized(
      'Climb 50m upward without touching the ground. A Piton or other climbing tool counts as touching the ground; Vines can be used.',
      '不接触地面向上攀爬 50 米。抓住 Piton 或其他攀爬工具会算作接触地面；可以使用 Vines。',
      'Sube 50 m sin tocar el suelo. Agarrar un Piton u otra herramienta de escalada cuenta como tocar el suelo; puedes usar Vines.',
      '地面に触れずに50m上へ登る。Pitonなどの登攀道具をつかむと地面に触れた扱いになり、Vinesは使える。',
      'Grimper de 50 m sans toucher le sol. S agripper à un Piton ou à un autre outil compte comme toucher le sol ; les Vines sont permises.',
      '50 m nach oben klettern, ohne den Boden zu berühren. Ein Piton oder ein anderes Kletterwerkzeug zählt als Bodenberührung; Vines sind erlaubt.',
      'Suba 50 m sem tocar o chão. Segurar um Piton ou outra ferramenta de escalada conta como tocar o chão; Vines podem ser usadas.',
      '지면에 닿지 않고 50m를 위로 등반하세요. Piton이나 다른 등반 도구를 잡으면 지면에 닿은 것으로 처리되며 Vines는 사용할 수 있습니다.',
      'Sali di 50 m senza toccare il terreno. Afferrare un Piton o un altro strumento conta come contatto; puoi usare le Vines.',
    ),
    grantKey: 'playerImmediate',
    reward: 'Ninja Headband',
  },
  {
    group: 'survival',
    name: 'Bundled Up Badge',
    condition: localized(
      'Climb past ALPINE without Cold ever exceeding 20%.',
      '爬过 ALPINE，Cold 从未超过 20%。',
      'Supera ALPINE sin que Cold supere nunca el 20%.',
      'Cold が20%を超えないまま ALPINE を越えて登る。',
      'Franchir ALPINE sans que Cold ne dépasse jamais 20 %.',
      'ALPINE überklettern, ohne dass Cold jemals über 20 % steigt.',
      'Suba além de ALPINE sem Cold passar de 20%.',
      'Cold가 한 번도 20%를 넘지 않게 ALPINE을 지나 등반하세요.',
      'Supera ALPINE senza che Cold superi mai il 20%.',
    ),
    grantKey: 'livingConditionCampfire',
    reward: 'Ice Blue + Ice Pink',
  },
  {
    group: 'survival',
    name: 'Cool Cucumber Badge',
    condition: localized(
      'Climb past MESA without Heat ever exceeding 10%.',
      '爬过 MESA，Heat 从未超过 10%。',
      'Supera MESA sin que Heat supere nunca el 10%.',
      'Heat が10%を超えないまま MESA を越えて登る。',
      'Franchir MESA sans que Heat ne dépasse jamais 10 %.',
      'MESA überklettern, ohne dass Heat jemals über 10 % steigt.',
      'Suba além de MESA sem Heat passar de 10%.',
      'Heat가 한 번도 10%를 넘지 않게 MESA를 지나 등반하세요.',
      'Supera MESA senza che Heat superi mai il 10%.',
    ),
    grantKey: 'livingConditionCampfire',
    reward: 'Gallon Hat + Cowboy Outfit',
  },
  {
    group: 'survival',
    name: 'Hasty Badge',
    condition: localized(
      'Escape the island in under one hour; escaping at exactly one hour also counts.',
      '在一小时内逃离岛屿；刚好一小时也算。',
      'Escapa de la isla en menos de una hora; escapar justo al cumplir una hora también cuenta.',
      '1時間以内に島から脱出する。ちょうど1時間でも達成になる。',
      'S évader de l île en moins d une heure ; exactement une heure compte aussi.',
      'Die Insel in weniger als einer Stunde verlassen; genau eine Stunde zählt ebenfalls.',
      'Escape da ilha em menos de uma hora; escapar exatamente em uma hora também conta.',
      '1시간 안에 섬에서 탈출하세요. 정확히 1시간에 탈출해도 인정됩니다.',
      'Fuggi dall isola in meno di un ora; anche esattamente un ora conta.',
    ),
    grantKey: 'escapeOnly',
    reward: 'Courier Hat',
  },
  {
    group: 'coop',
    name: 'Clutch Badge',
    condition: localized(
      'Revive 3 Scouts in a single expedition. Reviving the same Scout multiple times counts multiple times.',
      '单次远征复活 3 名 Scout；同一 Scout 多次复活可以重复计数。',
      'Reanima a 3 Scouts en una sola expedición. Reanimar varias veces al mismo Scout cuenta varias veces.',
      '1回の遠征でScoutを3人復活させる。同じScoutを複数回復活させても複数回として数える。',
      'Réanimer 3 Scouts lors d une expédition ; réanimer plusieurs fois le même Scout compte plusieurs fois.',
      'In einer Expedition 3 Scouts wiederbeleben. Mehrfaches Wiederbeleben desselben Scouts zählt mehrfach.',
      'Reanime 3 Scouts em uma única expedição. Reviver o mesmo Scout várias vezes conta várias vezes.',
      '한 번의 원정에서 Scout 3명을 부활시키세요. 같은 Scout을 여러 번 부활시켜도 여러 번으로 계산됩니다.',
      'Rianima 3 Scout in una spedizione. Rianimare più volte lo stesso Scout conta più volte.',
    ),
    grantKey: 'reviver',
    reward: 'Sailor Hat',
  },
  {
    group: 'coop',
    name: 'Emergency Preparedness Badge',
    condition: localized(
      'Use an item directly to lower an unconscious friend s total afflictions below 100 and save them. Faerie Lantern and Remedy Fungus do not count.',
      '直接使用物品，把昏迷队友的 total afflictions 降到 100 以下并救回。Faerie Lantern 与 Remedy Fungus 不计入。',
      'Usa un objeto directamente para bajar de 100 las afflictions totales de un amigo inconsciente y salvarlo. Faerie Lantern y Remedy Fungus no cuentan.',
      'アイテムを直接使い、意識を失った仲間のtotal afflictionsを100未満にして救う。Faerie LanternとRemedy Fungusは対象外。',
      'Utiliser directement un objet pour faire passer les afflictions totales d un ami inconscient sous 100 et le sauver. Faerie Lantern et Remedy Fungus ne comptent pas.',
      'Einen Gegenstand direkt einsetzen, um die gesamten Afflictions eines bewusstlosen Freundes unter 100 zu senken und ihn zu retten. Faerie Lantern und Remedy Fungus zählen nicht.',
      'Um item diretamente para reduzir as afflictions totais de um amigo inconsciente para menos de 100 e salvá-lo. Faerie Lantern e Remedy Fungus não contam.',
      '아이템을 직접 사용해 의식을 잃은 친구의 total afflictions를 100 아래로 낮추고 구하세요. Faerie Lantern과 Remedy Fungus는 인정되지 않습니다.',
      'Usa direttamente un oggetto per portare sotto 100 le afflictions totali di un amico privo di sensi e salvarlo. Faerie Lantern e Remedy Fungus non contano.',
    ),
    grantKey: 'directItem',
    reward: 'Sailor Outfit',
  },
  {
    group: 'coop',
    name: 'Disaster Response Badge',
    condition: localized(
      'Pull an unconscious friend 30m with Rescue Claw. The pulled Scout does not need to be unconscious at the start of the pull.',
      '用 Rescue Claw 拖拽昏迷队友 30 米；被拖拽的 Scout 在拖拽开始时不一定必须昏迷。',
      'Arrastra 30 m a un amigo inconsciente con Rescue Claw. El Scout arrastrado no tiene que estar inconsciente al comenzar el arrastre.',
      'Rescue Clawで意識を失った仲間を30m引く。引き始める時点で対象のScoutが意識を失っている必要はない。',
      'Tirer un ami inconscient sur 30 m avec Rescue Claw. Le Scout tiré n a pas besoin d être inconscient au début du tirage.',
      'Einen bewusstlosen Freund mit Rescue Claw 30 m ziehen. Der gezogene Scout muss zu Beginn des Ziehens nicht bewusstlos sein.',
      'Puxe um amigo inconsciente por 30 m com Rescue Claw. O Scout puxado não precisa estar inconsciente no início do puxão.',
      'Rescue Claw로 의식을 잃은 친구를 30m 끌어당기세요. 끌기 시작할 때 대상 Scout이 의식이 없어야 하는 것은 아닙니다.',
      'Trascina un amico privo di sensi per 30 m con Rescue Claw. Lo Scout trascinato non deve essere privo di sensi all inizio del tiro.',
    ),
    grantKey: 'rescueClaw',
    reward: 'Climbing Helmet + Climber Outfit',
  },
  {
    group: 'crafting',
    name: 'Bouldering Badge',
    condition: localized(
      'Place 10 Pitons across multiple expeditions.',
      '跨多次远征累计放置 10 个 Piton。',
      'Coloca 10 Pitons a lo largo de varias expediciones.',
      '複数の遠征で合計10本のPitonを設置する。',
      'Placer 10 Pitons au total sur plusieurs expéditions.',
      'Über mehrere Expeditionen insgesamt 10 Pitons platzieren.',
      'Coloque 10 Pitons ao longo de várias expedições.',
      '여러 원정에 걸쳐 Piton 10개를 설치하세요.',
      'Piazza 10 Piton complessivi in più spedizioni.',
    ),
    grantKey: 'piton',
    reward: 'Anime Eyes',
  },
  {
    group: 'crafting',
    name: 'Foraging Badge',
    condition: localized(
      'Eat 5 different berries in one expedition. Feeding a berry to another Scout counts for the feeder.',
      '单次远征吃 5 种不同的莓；喂给另一名 Scout 时计入喂食者。',
      'Come 5 bayas diferentes en una expedición. Dar una baya a otro Scout cuenta para quien la da.',
      '1回の遠征で異なるベリーを5種類食べる。別のScoutに食べさせた場合は、食べさせた側に加算される。',
      'Manger 5 baies différentes en une expédition. Donner une baie à un autre Scout compte pour celui qui la donne.',
      'In einer Expedition 5 verschiedene Beeren essen. Eine Beere an einen anderen Scout zu füttern zählt für die fütternde Person.',
      'Coma 5 frutas diferentes em uma expedição. Dar uma fruta a outro Scout conta para quem dá.',
      '한 번의 원정에서 서로 다른 베리 5종을 먹으세요. 다른 Scout에게 먹이면 먹인 사람의 진행으로 계산됩니다.',
      'Mangia 5 bacche diverse in una spedizione. Dare una bacca a un altro Scout conta per chi la dà.',
    ),
    grantKey: 'berry',
    reward: 'Wacky Mouth',
  },
  {
    group: 'crafting',
    name: 'Cooking Badge',
    condition: localized(
      'Cook 20 items at campfires across multiple expeditions; the item does not need to be edible.',
      '跨多次远征在营火烹饪 20 个物品；物品不必可食用。',
      'Cocina 20 objetos en hogueras a lo largo de varias expediciones; no tienen que ser comestibles.',
      '複数の遠征で焚き火で20個のアイテムを調理する。食べられるアイテムでなくてもよい。',
      'Cuisiner 20 objets sur des feux de camp au fil de plusieurs expéditions ; ils n ont pas besoin d être comestibles.',
      'Über mehrere Expeditionen 20 Gegenstände am Lagerfeuer kochen; sie müssen nicht essbar sein.',
      'Cozinhe 20 itens em fogueiras ao longo de várias expedições; eles não precisam ser comestíveis.',
      '여러 원정에 걸쳐 모닥불에서 아이템 20개를 요리하세요. 먹을 수 있는 아이템일 필요는 없습니다.',
      'Cucina 20 oggetti ai falò in più spedizioni; non devono essere commestibili.',
    ),
    grantKey: 'cooking',
    reward: 'Chef Hat',
  },
  {
    group: 'crafting',
    name: 'Gourmand Badge',
    condition: localized(
      'Cook and eat Half-Coconut, Honeycomb, Yellow Winterberry, and Egg, then escape alive. Feeding a required item counts for the feeder.',
      '烹饪并吃下 Half-Coconut、Honeycomb、Yellow Winterberry 和 Egg，之后活着逃离；喂食计入喂食者。',
      'Cocina y come Half-Coconut, Honeycomb, Yellow Winterberry y Egg, y después escapa con vida. Dar un objeto requerido cuenta para quien lo da.',
      'Half-Coconut、Honeycomb、Yellow Winterberry、Eggを調理して食べ、その後生きて脱出する。必要なアイテムを食べさせた場合は食べさせた側に加算される。',
      'Cuisiner et manger Half-Coconut, Honeycomb, Yellow Winterberry et Egg, puis s évader vivant. Donner un objet requis compte pour celui qui le donne.',
      'Half-Coconut, Honeycomb, Yellow Winterberry und Egg kochen und essen, dann lebend entkommen. Das Füttern eines erforderlichen Gegenstands zählt für die fütternde Person.',
      'Cozinhe e coma Half-Coconut, Honeycomb, Yellow Winterberry e Egg, depois escape vivo. Dar um item necessário conta para quem dá.',
      'Half-Coconut, Honeycomb, Yellow Winterberry, Egg를 요리해 먹고 살아서 탈출하세요. 필요한 아이템을 먹이면 먹인 사람의 진행으로 계산됩니다.',
      'Cucina e mangia Half-Coconut, Honeycomb, Yellow Winterberry ed Egg, poi fuggi vivo. Dare un oggetto richiesto conta per chi lo dà.',
    ),
    grantKey: 'escapeAlive',
    reward: 'Aggro Mouth + Aggro Eyes',
  },
  {
    group: 'crafting',
    name: 'Cryptogastronomy Badge',
    condition: localized(
      'Cook and eat a Mandrake. You do not need to be the player who cooked it.',
      '烹饪并吃掉 Mandrake；不必由你亲自烹饪。',
      'Cocina y come un Mandrake. No tienes que haberlo cocinado tú.',
      'Mandrakeを調理して食べる。自分で調理する必要はない。',
      'Cuisiner et manger un Mandrake. Il n est pas nécessaire de l avoir cuisiné soi-même.',
      'Eine Mandrake kochen und essen. Du musst sie nicht selbst gekocht haben.',
      'Cozinhe e coma um Mandrake. Você não precisa ter sido quem o cozinhou.',
      'Mandrake를 요리해 먹으세요. 직접 요리할 필요는 없습니다.',
      'Cucina e mangia un Mandrake. Non devi essere tu ad averlo cucinato.',
    ),
    grantKey: 'mandrake',
    reward: 'Sprout Hat',
  },
  {
    group: 'newMaps',
    name: 'Bellringer Badge',
    condition: localized(
      'Ring 5 Belltowers in GLOOM in a single expedition.',
      '单次远征在 GLOOM 敲响 5 座 Belltower。',
      'Toca 5 Belltowers en GLOOM durante una sola expedición.',
      '1回の遠征でGLOOMのBelltowerを5基鳴らす。',
      'Faire sonner 5 Belltowers dans GLOOM au cours d une expédition.',
      'In einer Expedition 5 Belltowers in GLOOM läuten.',
      'Toque 5 Belltowers em GLOOM em uma única expedição.',
      '한 번의 원정에서 GLOOM의 Belltower 5개를 울리세요.',
      'Suona 5 Belltower in GLOOM in una spedizione.',
    ),
    grantKey: 'allPlayers',
    reward: 'Frog Hat',
    patchKey: 'patch203Context',
  },
  {
    group: 'newMaps',
    name: 'Exorcist Badge',
    condition: localized(
      'Burn up the Big Ghost in GLOOM using Candlestick, Faerie Lantern, Lantern, Portable Stove, or a Belltower.',
      '在 GLOOM 使用 Candlestick、Faerie Lantern、Lantern、Portable Stove 或 Belltower 烧死 Big Ghost。',
      'Quema al Big Ghost de GLOOM con Candlestick, Faerie Lantern, Lantern, Portable Stove o un Belltower.',
      'GLOOMのBig Ghostを、Candlestick、Faerie Lantern、Lantern、Portable Stove、またはBelltowerで焼き尽くす。',
      'Brûler le Big Ghost de GLOOM avec Candlestick, Faerie Lantern, Lantern, Portable Stove ou un Belltower.',
      'Den Big Ghost in GLOOM mit Candlestick, Faerie Lantern, Lantern, Portable Stove oder einem Belltower verbrennen.',
      'Queime o Big Ghost de GLOOM usando Candlestick, Faerie Lantern, Lantern, Portable Stove ou um Belltower.',
      'GLOOM의 Big Ghost를 Candlestick, Faerie Lantern, Lantern, Portable Stove 또는 Belltower로 태우세요.',
      'Brucia il Big Ghost di GLOOM usando Candlestick, Faerie Lantern, Lantern, Portable Stove o un Belltower.',
    ),
    grantKey: 'allPlayersGhost',
    reward: 'Gothic Hat + Gothic Outfit',
    patchKey: 'patch203Context',
  },
  {
    group: 'newMaps',
    name: 'Medieval History Badge',
    condition: localized(
      'Climb past THE CITADEL without being hit by traps. Petrified Rocks do not count as a trap hit.',
      '不被陷阱击中爬过 THE CITADEL；Petrified Rocks 不算陷阱命中。',
      'Supera THE CITADEL sin recibir golpes de trampas. Petrified Rocks no cuentan como golpe de trampa.',
      '罠に当たらずにTHE CITADELを越えて登る。Petrified Rocksは罠の命中に数えない。',
      'Franchir THE CITADEL sans être touché par un piège. Petrified Rocks ne comptent pas comme un piège.',
      'THE CITADEL überklettern, ohne von Fallen getroffen zu werden. Petrified Rocks zählen nicht als Fallentreffer.',
      'Suba além de THE CITADEL sem ser atingido por armadilhas. Petrified Rocks não contam como um acerto de armadilha.',
      '함정에 맞지 않고 THE CITADEL을 지나 등반하세요. Petrified Rocks는 함정에 맞은 것으로 계산되지 않습니다.',
      'Supera THE CITADEL senza essere colpito dalle trappole. Petrified Rocks non conta come colpo di trappola.',
    ),
    grantKey: 'citadel',
    reward: 'Knight Hat + Knight Outfit',
    patchKey: 'patch204Context',
  },
  {
    group: 'newMaps',
    name: '24 Karat Badge',
    condition: localized(
      'In MESA, find the Tomb, complete its parkour puzzle, take the Ancient Idol to The Kiln or The Citadel, and drop it into lava.',
      '在 MESA 找到 Tomb，完成跑酷谜题，把 Ancient Idol 带到 The Kiln 或 The Citadel 并投入岩浆。',
      'En MESA, encuentra la Tomb, completa su rompecabezas de parkour, lleva el Ancient Idol a The Kiln o The Citadel y tíralo a la lava.',
      'MESAでTombを見つけ、パルクールパズルを解き、Ancient IdolをThe KilnまたはThe Citadelへ運んで溶岩に落とす。',
      'Dans MESA, trouver la Tomb, terminer son parcours, porter l Ancient Idol à The Kiln ou The Citadel et le jeter dans la lave.',
      'In MESA die Tomb finden, das Parkour-Rätsel lösen, das Ancient Idol zu The Kiln oder The Citadel bringen und in die Lava werfen.',
      'Em MESA, encontre a Tomb, conclua o quebra-cabeça de parkour, leve o Ancient Idol ao The Kiln ou The Citadel e jogue-o na lava.',
      'MESA에서 Tomb을 찾고 파쿠르 퍼즐을 완료한 뒤 Ancient Idol을 The Kiln 또는 The Citadel로 가져가 용암에 던지세요.',
      'In MESA trova la Tomb, completa il percorso parkour, porta l Ancient Idol a The Kiln o The Citadel e gettalo nella lava.',
    ),
    grantKey: 'idolLiving',
    reward: 'Bing Bong Beanie',
    patchKey: 'patch204Context',
    spoiler: true,
  },
];

const grantCopy = {
  en: {
    campfireLiving: 'All living players when the end campfire is lit, including players just revived.',
    playerImmediate: 'The completing player; awarded immediately.',
    livingConditionCampfire: 'All living players who meet the condition when the end campfire is lit.',
    escapeOnly: 'The player must escape; being alive at the end is not enough.',
    reviver: 'The player who revives the third Scout; awarded immediately.',
    directItem: 'The player who directly uses the qualifying item.',
    rescueClaw: 'The Rescue Claw user after the pull reaches 30m.',
    piton: 'The player who places the 10th Piton; progress spans expeditions.',
    berry: 'The player who eats the fifth berry; feeding counts for the feeder.',
    cooking: 'The player who cooks the 20th item; progress spans expeditions.',
    escapeAlive: 'The player who escapes alive after meeting the food requirements.',
    mandrake: 'The player who eats or is fed cooked Mandrake.',
    allPlayers: 'All players, living or dead, when the fifth bell is rung.',
    allPlayersGhost: 'All players, living or dead, immediately when Big Ghost dies.',
    citadel: 'The player who reaches the top of THE CITADEL.',
    idolLiving: 'All living players when the idol is destroyed, regardless of who throws it.',
  },
  zh: {
    campfireLiving: '终点营火点亮时，所有存活玩家获得，包括刚复活的玩家。',
    playerImmediate: '完成条件的玩家立即获得。',
    livingConditionCampfire: '满足条件的所有存活玩家在终点营火点亮时获得。',
    escapeOnly: '必须实际逃离；只是在结束时存活并不够。',
    reviver: '复活第三名 Scout 的玩家立即获得。',
    directItem: '直接使用符合条件物品的玩家获得。',
    rescueClaw: '拖拽达到 30 米后，使用 Rescue Claw 的玩家获得。',
    piton: '放置第 10 个 Piton 的玩家获得；进度跨远征累计。',
    berry: '吃下第 5 种莓的玩家获得；喂食计入喂食者。',
    cooking: '烹饪第 20 个物品的玩家获得；进度跨远征累计。',
    escapeAlive: '满足食物条件并活着逃离的玩家获得。',
    mandrake: '吃到或被喂到 cooked Mandrake 的玩家获得。',
    allPlayers: '第 5 座钟敲响时，所有玩家，无论存活或阵亡，都获得。',
    allPlayersGhost: 'Big Ghost 死亡时，所有玩家，无论存活或阵亡，都立即获得。',
    citadel: '到达 THE CITADEL 顶端的玩家获得。',
    idolLiving: 'Ancient Idol 被摧毁时，所有存活玩家获得，与谁投入无关。',
  },
  es: {
    campfireLiving: 'Todos los jugadores vivos cuando se enciende la hoguera final, incluso quienes acaban de ser reanimados.',
    playerImmediate: 'El jugador que completa la condición; se concede al instante.',
    livingConditionCampfire: 'Todos los jugadores vivos que cumplen la condición cuando se enciende la hoguera final.',
    escapeOnly: 'Hay que escapar; estar vivo al final no basta.',
    reviver: 'El jugador que reanima al tercer Scout; se concede al instante.',
    directItem: 'El jugador que usa directamente el objeto válido.',
    rescueClaw: 'El usuario de Rescue Claw cuando el arrastre alcanza 30 m.',
    piton: 'El jugador que coloca el décimo Piton; el progreso se acumula entre expediciones.',
    berry: 'El jugador que come la quinta baya; dar comida cuenta para quien la da.',
    cooking: 'El jugador que cocina el vigésimo objeto; el progreso se acumula entre expediciones.',
    escapeAlive: 'El jugador que escapa con vida después de cumplir los requisitos de comida.',
    mandrake: 'El jugador que come o recibe un Mandrake cocinado.',
    allPlayers: 'Todos los jugadores, vivos o muertos, cuando suena la quinta campana.',
    allPlayersGhost: 'Todos los jugadores, vivos o muertos, en cuanto muere el Big Ghost.',
    citadel: 'El jugador que alcanza la cima de THE CITADEL.',
    idolLiving: 'Todos los jugadores vivos cuando se destruye el ídolo, sin importar quién lo lance.',
  },
  ja: {
    campfireLiving: '最後の焚き火が点火された時点で生存している全員。直前に復活したプレイヤーも含む。',
    playerImmediate: '条件を達成したプレイヤーに即時付与。',
    livingConditionCampfire: '条件を満たした生存プレイヤー全員に、最後の焚き火が点火された時点で付与。',
    escapeOnly: '実際に脱出する必要があり、終了時に生存しているだけでは足りない。',
    reviver: '3人目のScoutを復活させたプレイヤーに即時付与。',
    directItem: '条件を満たすアイテムを直接使ったプレイヤーに付与。',
    rescueClaw: '引っ張った距離が30mに達した時点で、Rescue Clawを使ったプレイヤーに付与。',
    piton: '10本目のPitonを設置したプレイヤー。進行は遠征をまたいで累積する。',
    berry: '5種類目のベリーを食べたプレイヤー。食べさせた場合は食べさせた側に加算される。',
    cooking: '20個目を調理したプレイヤー。進行は遠征をまたいで累積する。',
    escapeAlive: '食べ物の条件を満たした後、生きて脱出したプレイヤーに付与。',
    mandrake: '調理済みのMandrakeを食べた、または食べさせてもらったプレイヤー。',
    allPlayers: '5基目の鐘が鳴った時点で、生存・死亡を問わず全員に付与。',
    allPlayersGhost: 'Big Ghostが倒れた時点で、生存・死亡を問わず全員に即時付与。',
    citadel: 'THE CITADELの頂上に到達したプレイヤーに付与。',
    idolLiving: 'Ancient Idolが壊れた時点で、誰が投げたかに関係なく生存プレイヤー全員に付与。',
  },
  fr: {
    campfireLiving: 'Tous les joueurs vivants lorsque le feu de camp final est allumé, y compris ceux qui viennent d être réanimés.',
    playerImmediate: 'Le joueur qui remplit la condition ; attribution immédiate.',
    livingConditionCampfire: 'Tous les joueurs vivants qui remplissent la condition lorsque le feu final est allumé.',
    escapeOnly: 'Il faut s évader ; être vivant à la fin ne suffit pas.',
    reviver: 'Le joueur qui réanime le troisième Scout ; attribution immédiate.',
    directItem: 'Le joueur qui utilise directement l objet admissible.',
    rescueClaw: 'L utilisateur de Rescue Claw lorsque le tirage atteint 30 m.',
    piton: 'Le joueur qui pose le 10e Piton ; la progression se cumule entre les expéditions.',
    berry: 'Le joueur qui mange la cinquième baie ; nourrir quelqu un compte pour celui qui nourrit.',
    cooking: 'Le joueur qui cuisine le 20e objet ; la progression se cumule entre les expéditions.',
    escapeAlive: 'Le joueur qui s évade vivant après avoir rempli les conditions alimentaires.',
    mandrake: 'Le joueur qui mange ou reçoit un Mandrake cuisiné.',
    allPlayers: 'Tous les joueurs, vivants ou morts, lorsque la cinquième cloche sonne.',
    allPlayersGhost: 'Tous les joueurs, vivants ou morts, dès que le Big Ghost meurt.',
    citadel: 'Le joueur qui atteint le sommet de THE CITADEL.',
    idolLiving: 'Tous les joueurs vivants lorsque l idole est détruite, quelle que soit la personne qui la jette.',
  },
  de: {
    campfireLiving: 'Alle lebenden Spieler, sobald das Endlagerfeuer entzündet wird, einschließlich gerade wiederbelebter Spieler.',
    playerImmediate: 'Der Spieler, der die Bedingung erfüllt; sofortige Vergabe.',
    livingConditionCampfire: 'Alle lebenden Spieler, die die Bedingung erfüllen, sobald das Endlagerfeuer brennt.',
    escapeOnly: 'Die Person muss entkommen; am Ende nur am Leben zu sein reicht nicht.',
    reviver: 'Der Spieler, der den dritten Scout wiederbelebt; sofortige Vergabe.',
    directItem: 'Der Spieler, der den passenden Gegenstand direkt einsetzt.',
    rescueClaw: 'Der Rescue-Claw-Nutzer, sobald der Zug 30 m erreicht.',
    piton: 'Der Spieler, der den 10. Piton platziert; der Fortschritt wird über Expeditionen gesammelt.',
    berry: 'Der Spieler, der die fünfte Beere isst; Füttern zählt für die fütternde Person.',
    cooking: 'Der Spieler, der den 20. Gegenstand kocht; der Fortschritt wird über Expeditionen gesammelt.',
    escapeAlive: 'Der Spieler, der nach den Essensbedingungen lebend entkommt.',
    mandrake: 'Der Spieler, der eine gekochte Mandrake isst oder gefüttert bekommt.',
    allPlayers: 'Alle Spieler, lebend oder tot, sobald die fünfte Glocke läutet.',
    allPlayersGhost: 'Alle Spieler, lebend oder tot, sobald der Big Ghost stirbt.',
    citadel: 'Der Spieler, der den Gipfel von THE CITADEL erreicht.',
    idolLiving: 'Alle lebenden Spieler, sobald das Idol zerstört wird, unabhängig davon, wer es wirft.',
  },
  pt: {
    campfireLiving: 'Todos os jogadores vivos quando a fogueira final é acesa, incluindo quem acabou de ser revivido.',
    playerImmediate: 'O jogador que conclui a condição; concedido imediatamente.',
    livingConditionCampfire: 'Todos os jogadores vivos que cumprem a condição quando a fogueira final é acesa.',
    escapeOnly: 'É preciso escapar; estar vivo no fim não basta.',
    reviver: 'O jogador que revive o terceiro Scout; concedido imediatamente.',
    directItem: 'O jogador que usa diretamente o item válido.',
    rescueClaw: 'O usuário de Rescue Claw quando o puxão chega a 30 m.',
    piton: 'O jogador que coloca o 10º Piton; o progresso acumula entre expedições.',
    berry: 'O jogador que come a quinta fruta; alimentar alguém conta para quem alimenta.',
    cooking: 'O jogador que cozinha o 20º item; o progresso acumula entre expedições.',
    escapeAlive: 'O jogador que escapa vivo depois de cumprir os requisitos de comida.',
    mandrake: 'O jogador que come ou recebe um Mandrake cozido.',
    allPlayers: 'Todos os jogadores, vivos ou mortos, quando o quinto sino toca.',
    allPlayersGhost: 'Todos os jogadores, vivos ou mortos, assim que o Big Ghost morre.',
    citadel: 'O jogador que chega ao topo de THE CITADEL.',
    idolLiving: 'Todos os jogadores vivos quando o ídolo é destruído, independentemente de quem o jogou.',
  },
  ko: {
    campfireLiving: '마지막 모닥불이 켜질 때 살아 있는 모든 플레이어에게 적용됩니다. 방금 부활한 플레이어도 포함됩니다.',
    playerImmediate: '조건을 완료한 플레이어에게 즉시 적용됩니다.',
    livingConditionCampfire: '조건을 충족한 살아 있는 모든 플레이어에게 마지막 모닥불이 켜질 때 적용됩니다.',
    escapeOnly: '실제로 탈출해야 합니다. 마지막에 살아 있기만 해서는 충분하지 않습니다.',
    reviver: '세 번째 Scout을 부활시킨 플레이어에게 즉시 적용됩니다.',
    directItem: '조건에 맞는 아이템을 직접 사용한 플레이어에게 적용됩니다.',
    rescueClaw: '끌어당긴 거리가 30m에 도달하면 Rescue Claw 사용자에게 적용됩니다.',
    piton: 'Piton 10번째를 설치한 플레이어에게 적용됩니다. 진행도는 여러 원정에 걸쳐 누적됩니다.',
    berry: '다섯 번째 베리를 먹은 플레이어에게 적용됩니다. 먹여 주면 먹인 사람의 진행으로 계산됩니다.',
    cooking: '20번째 아이템을 요리한 플레이어에게 적용됩니다. 진행도는 여러 원정에 걸쳐 누적됩니다.',
    escapeAlive: '음식 조건을 충족한 뒤 살아서 탈출한 플레이어에게 적용됩니다.',
    mandrake: '요리한 Mandrake를 먹거나 먹여 받은 플레이어에게 적용됩니다.',
    allPlayers: '다섯 번째 종이 울리면 살아 있거나 죽은 모든 플레이어에게 적용됩니다.',
    allPlayersGhost: 'Big Ghost가 죽는 즉시 살아 있거나 죽은 모든 플레이어에게 적용됩니다.',
    citadel: 'THE CITADEL 정상에 도달한 플레이어에게 적용됩니다.',
    idolLiving: '우상을 누가 던졌는지와 관계없이 Ancient Idol이 파괴되면 살아 있는 모든 플레이어에게 적용됩니다.',
  },
  it: {
    campfireLiving: 'Tutti i giocatori vivi quando viene acceso il falò finale, compresi quelli appena rianimati.',
    playerImmediate: 'Il giocatore che completa la condizione; assegnato subito.',
    livingConditionCampfire: 'Tutti i giocatori vivi che soddisfano la condizione quando viene acceso il falò finale.',
    escapeOnly: 'È necessario fuggire; essere vivi alla fine non basta.',
    reviver: 'Il giocatore che rianima il terzo Scout; assegnato subito.',
    directItem: 'Il giocatore che usa direttamente l oggetto valido.',
    rescueClaw: 'L utilizzatore di Rescue Claw quando il tiro raggiunge 30 m.',
    piton: 'Il giocatore che piazza il 10° Piton; il progresso si accumula tra le spedizioni.',
    berry: 'Il giocatore che mangia la quinta bacca; dare da mangiare conta per chi la dà.',
    cooking: 'Il giocatore che cucina il 20° oggetto; il progresso si accumula tra le spedizioni.',
    escapeAlive: 'Il giocatore che fugge vivo dopo aver soddisfatto i requisiti alimentari.',
    mandrake: 'Il giocatore che mangia o riceve una Mandrake cotta.',
    allPlayers: 'Tutti i giocatori, vivi o morti, quando suona la quinta campana.',
    allPlayersGhost: 'Tutti i giocatori, vivi o morti, appena muore il Big Ghost.',
    citadel: 'Il giocatore che raggiunge la cima di THE CITADEL.',
    idolLiving: 'Tutti i giocatori vivi quando l idolo viene distrutto, indipendentemente da chi lo lancia.',
  },
};

const commonLabels = {
  en: { condition: 'Unlock condition', grant: 'Granted to', reward: 'Cosmetic reward', source: 'Source note', spoiler: 'Spoiler', patch: 'Version context' },
  zh: { condition: '解锁条件', grant: '授予范围', reward: 'Cosmetic 奖励', source: '来源说明', spoiler: '剧透', patch: '版本背景' },
  es: { condition: 'Condición de desbloqueo', grant: 'Se concede a', reward: 'Recompensa cosmética', source: 'Nota de fuente', spoiler: 'Spoiler', patch: 'Contexto de versión' },
  ja: { condition: '解除条件', grant: '付与範囲', reward: 'Cosmetic報酬', source: '出典メモ', spoiler: 'ネタバレ', patch: 'バージョン背景' },
  fr: { condition: 'Condition de déblocage', grant: 'Attribué à', reward: 'Récompense cosmétique', source: 'Note de source', spoiler: 'Spoiler', patch: 'Contexte de version' },
  de: { condition: 'Freischaltbedingung', grant: 'Vergabe an', reward: 'Cosmetic-Belohnung', source: 'Quellenhinweis', spoiler: 'Spoiler', patch: 'Versionskontext' },
  pt: { condition: 'Condição de desbloqueio', grant: 'Concedido a', reward: 'Recompensa cosmética', source: 'Nota da fonte', spoiler: 'Spoiler', patch: 'Contexto da versão' },
  ko: { condition: '잠금 해제 조건', grant: '적용 대상', reward: 'Cosmetic 보상', source: '출처 메모', spoiler: '스포일러', patch: '버전 배경' },
  it: { condition: 'Condizione di sblocco', grant: 'Assegnato a', reward: 'Ricompensa cosmetica', source: 'Nota sulla fonte', spoiler: 'Spoiler', patch: 'Contesto della versione' },
};

const groupCopy = {
  en: {
    route: { title: 'Route and summit badges', intro: 'These route entries reward reaching named biomes. The end-campfire wording matters: they are not automatically awarded to every player who started the expedition.' },
    survival: { title: 'Survival challenge badges', intro: 'These entries turn a route into a measurable constraint: height, Cold, Heat, or an escape time. Read the exact threshold before treating a failed attempt as a bug.' },
    coop: { title: 'Co-op rescue badges', intro: 'The source distinguishes the player who performs the rescue from the player being helped. Keep that ownership visible when planning a team attempt.' },
    crafting: { title: 'Gathering, cooking, and cumulative badges', intro: 'Some progress is immediate and some is tracked across expeditions. Feeding and cooking credit belongs to the player described in each source note, not to a generic team total.' },
    newMaps: { title: 'GLOOM, CITADEL, and KILN context', intro: 'These representative entries connect badge play with newer route contexts. The patch labels below are map and version context, not a claim that every badge was added in that patch.' },
  },
  zh: {
    route: { title: '登顶路线类徽章', intro: '这些条目奖励你爬过指定生物群系。终点营火的授予条件很重要：不是所有开始远征的人都会自动获得。' },
    survival: { title: '生存挑战类徽章', intro: '这些条目把路线变成可测量的限制：高度、Cold、Heat 或逃离时间。先看清阈值，再判断失败是否真的属于异常。' },
    coop: { title: '合作救援类徽章', intro: '来源会区分执行救援的玩家与被帮助的玩家。准备团队挑战时，应保留这种归属差异。' },
    crafting: { title: '采集、烹饪与累计进度类徽章', intro: '有些进度立即结算，有些会跨远征累计。喂食和烹饪的计数归属以每条来源说明为准，不要笼统算作团队总数。' },
    newMaps: { title: 'GLOOM、CITADEL 与 KILN 背景', intro: '这些代表条目把徽章玩法与较新的路线背景连接起来。下方补丁标记是地图和版本背景，不表示每个徽章都在该补丁新增。' },
  },
  es: {
    route: { title: 'Insignias de ruta y cima', intro: 'Estas entradas premian superar biomas concretos. La condición de la hoguera final importa: no se conceden automáticamente a todos los que empezaron la expedición.' },
    survival: { title: 'Insignias de desafíos de supervivencia', intro: 'Estas entradas convierten la ruta en una restricción medible: altura, Cold, Heat o tiempo de escape. Lee el umbral antes de tratar un fallo como un error.' },
    coop: { title: 'Insignias de rescate cooperativo', intro: 'La fuente distingue al jugador que realiza el rescate del jugador que recibe ayuda. Mantén esa atribución al preparar el intento.' },
    crafting: { title: 'Insignias de recolección, cocina y progreso acumulado', intro: 'Algunos progresos son inmediatos y otros se acumulan entre expediciones. La fuente indica quién recibe el crédito por alimentar o cocinar; no lo conviertas en un total de equipo.' },
    newMaps: { title: 'Contexto de GLOOM, CITADEL y KILN', intro: 'Estas entradas conectan las insignias con contextos de ruta recientes. Las etiquetas de parche son contexto de mapa y versión, no una afirmación de que cada insignia se añadiera en ese parche.' },
  },
  ja: {
    route: { title: 'ルート・登頂系バッジ', intro: '指定されたバイオームを越えて登ることで得られる項目です。最後の焚き火で付与される条件があるため、遠征を始めた全員に自動付与されるとは限りません。' },
    survival: { title: 'サバイバルチャレンジ系バッジ', intro: '高さ、Cold、Heat、脱出時間など、ルートに測定可能な制約を加える項目です。失敗を不具合と判断する前に、しきい値を確認してください。' },
    coop: { title: '協力救助系バッジ', intro: '出典では救助を行うプレイヤーと助けられるプレイヤーを区別しています。チームで挑戦する際も、この付与対象を分けて考えます。' },
    crafting: { title: '採集・調理・累積系バッジ', intro: 'すぐに付与される進行と、遠征をまたいで累積する進行があります。食べさせる行為や調理のクレジットは各項目の出典メモに従います。' },
    newMaps: { title: 'GLOOM・CITADEL・KILNの背景', intro: '新しいルート背景とバッジの遊び方をつなぐ代表例です。下のパッチ表示はマップとバージョンの文脈であり、各バッジがそのパッチで追加されたという意味ではありません。' },
  },
  fr: {
    route: { title: 'Badges de route et de sommet', intro: 'Ces entrées récompensent le franchissement de biomes nommés. La condition du feu final compte : le badge n est pas automatiquement attribué à tous les membres du départ.' },
    survival: { title: 'Badges de défis de survie', intro: 'Ces entrées imposent une contrainte mesurable : hauteur, Cold, Heat ou temps d évasion. Vérifiez le seuil exact avant de conclure à un problème.' },
    coop: { title: 'Badges de sauvetage coopératif', intro: 'La source distingue le joueur qui effectue le sauvetage de celui qui est aidé. Gardez cette attribution lorsque vous préparez la tentative.' },
    crafting: { title: 'Badges de collecte, cuisine et progression cumulée', intro: 'Certaines progressions sont immédiates, d autres se cumulent entre les expéditions. Le crédit de nourriture et de cuisine suit chaque note de source, pas un total d équipe vague.' },
    newMaps: { title: 'Contexte de GLOOM, CITADEL et KILN', intro: 'Ces entrées relient les badges aux contextes de route récents. Les mentions de patch décrivent le contexte de la carte et de la version, pas l ajout de chaque badge dans ce patch.' },
  },
  de: {
    route: { title: 'Routen- und Gipfel-Abzeichen', intro: 'Diese Einträge belohnen das Überklettern benannter Biome. Die Bedingung mit dem Endlagerfeuer ist wichtig: Nicht jeder Expeditionsstart erhält das Abzeichen automatisch.' },
    survival: { title: 'Abzeichen für Überlebensherausforderungen', intro: 'Diese Einträge machen die Route zu einer messbaren Einschränkung: Höhe, Cold, Heat oder Fluchtzeit. Prüfe den genauen Schwellenwert, bevor du einen Fehlschlag als Fehler wertest.' },
    coop: { title: 'Abzeichen für Rettung im Koop', intro: 'Die Quelle unterscheidet zwischen dem rettenden Spieler und der geholfenen Person. Diese Vergabe solltest du bei einem Teamversuch sichtbar halten.' },
    crafting: { title: 'Abzeichen für Sammeln, Kochen und kumulierten Fortschritt', intro: 'Mancher Fortschritt wird sofort vergeben, anderer sammelt sich über Expeditionen. Füttern und Kochen zählen entsprechend dem jeweiligen Quellenhinweis, nicht als pauschale Teamzahl.' },
    newMaps: { title: 'Kontext für GLOOM, CITADEL und KILN', intro: 'Diese Beispiele verbinden Abzeichen mit neueren Routen. Die Patchangaben liefern Karten- und Versionskontext und behaupten nicht, dass jedes Abzeichen in diesem Patch hinzugefügt wurde.' },
  },
  pt: {
    route: { title: 'Distintivos de rota e cume', intro: 'Estas entradas recompensam passar por biomas nomeados. A condição da fogueira final importa: o distintivo não é concedido automaticamente a todos que começaram a expedição.' },
    survival: { title: 'Distintivos de desafios de sobrevivência', intro: 'Estas entradas transformam a rota em uma restrição mensurável: altura, Cold, Heat ou tempo de fuga. Confira o limite antes de tratar uma falha como erro.' },
    coop: { title: 'Distintivos de resgate cooperativo', intro: 'A fonte separa quem realiza o resgate de quem recebe ajuda. Mantenha essa atribuição clara ao planejar a tentativa em equipe.' },
    crafting: { title: 'Distintivos de coleta, cozinha e progresso acumulado', intro: 'Alguns progressos são imediatos e outros acumulam entre expedições. O crédito de alimentar e cozinhar segue a nota de cada fonte, não um total genérico da equipe.' },
    newMaps: { title: 'Contexto de GLOOM, CITADEL e KILN', intro: 'Estas entradas ligam os distintivos a contextos recentes de rota. As etiquetas de patch são contexto de mapa e versão, não uma afirmação de que cada distintivo foi adicionado naquele patch.' },
  },
  ko: {
    route: { title: '경로 및 정상 배지', intro: '이 항목들은 이름이 지정된 생물군계를 지나 등반했을 때 보상합니다. 마지막 모닥불 조건이 중요하므로 원정을 시작한 모든 플레이어에게 자동으로 적용되는 것은 아닙니다.' },
    survival: { title: '생존 도전 배지', intro: '높이, Cold, Heat, 탈출 시간처럼 측정 가능한 제한을 추가하는 항목입니다. 실패를 오류로 판단하기 전에 정확한 기준을 확인하세요.' },
    coop: { title: '협동 구조 배지', intro: '출처는 구조를 수행한 플레이어와 도움을 받은 플레이어를 구분합니다. 팀 도전을 준비할 때 이 적용 대상을 분명히 기록하세요.' },
    crafting: { title: '채집, 요리 및 누적 진행 배지', intro: '즉시 적용되는 진행과 여러 원정에 걸쳐 누적되는 진행이 있습니다. 먹이기와 요리의 크레딧은 각 출처 메모에 따르며 팀 전체 수치로 뭉뚱그리지 않습니다.' },
    newMaps: { title: 'GLOOM, CITADEL, KILN 버전 배경', intro: '새로운 경로 맥락과 배지 플레이를 연결하는 대표 항목입니다. 아래 패치 표시는 맵과 버전 배경이며 모든 배지가 해당 패치에서 추가되었다는 뜻은 아닙니다.' },
  },
  it: {
    route: { title: 'Badge di percorso e vetta', intro: 'Queste voci premiano il superamento di biomi nominati. La condizione del falò finale conta: il badge non viene assegnato automaticamente a tutti quelli che hanno iniziato la spedizione.' },
    survival: { title: 'Badge delle sfide di sopravvivenza', intro: 'Queste voci aggiungono un vincolo misurabile: altezza, Cold, Heat o tempo di fuga. Leggi la soglia prima di chiamare un fallimento un errore.' },
    coop: { title: 'Badge di soccorso cooperativo', intro: 'La fonte distingue chi esegue il soccorso da chi riceve aiuto. Mantieni questa attribuzione quando prepari il tentativo.' },
    crafting: { title: 'Badge di raccolta, cucina e progresso cumulativo', intro: 'Alcuni progressi sono immediati, altri si accumulano tra le spedizioni. Il credito per nutrire e cucinare segue la nota della singola fonte, non un totale generico della squadra.' },
    newMaps: { title: 'Contesto di GLOOM, CITADEL e KILN', intro: 'Queste voci collegano i badge ai contesti recenti dei percorsi. Le etichette delle patch sono contesto di mappa e versione, non la prova che ogni badge sia stato aggiunto in quella patch.' },
  },
};

const groupImages = {
  en: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'A PEAK climber approaching a named biome route', caption: 'Official Steam screenshot used as route context; the badge condition still needs an in-game check.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: 'Official PEAK Final Ascent artwork beneath a changing route context', caption: 'Official Steam artwork used as version context, not as proof of a badge condition.' },
  },
  zh: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'PEAK 玩家接近指定生物群系路线的游戏截图', caption: 'Steam 官方截图用于说明路线背景；徽章条件仍需在游戏内核对。' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: '展示 PEAK 版本路线背景的官方 Final Ascent 美术图', caption: 'Steam 官方美术图用于说明版本背景，不证明某项徽章条件。' },
  },
  es: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'Captura de PEAK con un jugador acercándose a una ruta de bioma', caption: 'Captura oficial de Steam como contexto de ruta; la condición debe confirmarse dentro del juego.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: 'Arte oficial de PEAK Final Ascent como contexto de una ruta cambiante', caption: 'Arte oficial de Steam como contexto de versión, no como prueba de una condición.' },
  },
  ja: {
    route: { src: '/media/peak-climb-ridge.webp', alt: '指定バイオームのルートへ向かう PEAK のゲーム画面', caption: 'Steam公式スクリーンショットはルートの背景用です。バッジ条件はゲーム内で確認してください。' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: '変化するルートの背景を示す公式 PEAK Final Ascent アート', caption: 'Steam公式アートはバージョンの背景であり、バッジ条件の証明ではありません。' },
  },
  fr: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'Capture de PEAK montrant un grimpeur près d une route de biome', caption: 'Capture officielle Steam pour le contexte de route ; la condition doit être vérifiée dans le jeu.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: 'Illustration officielle PEAK Final Ascent comme contexte de route variable', caption: 'Illustration officielle Steam pour le contexte de version, pas pour prouver une condition.' },
  },
  de: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'PEAK-Spielszene mit einem Kletterer auf dem Weg zu einem Biom', caption: 'Offizieller Steam-Screenshot als Routen-Kontext; die Abzeichenbedingung muss im Spiel geprüft werden.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: 'Offizielle PEAK-Final-Ascent-Grafik als Kontext für eine wechselnde Route', caption: 'Offizielle Steam-Grafik als Versionskontext, nicht als Beweis einer Abzeichenbedingung.' },
  },
  pt: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'Captura de PEAK com um jogador se aproximando de uma rota de bioma', caption: 'Captura oficial da Steam como contexto da rota; a condição deve ser confirmada no jogo.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: 'Arte oficial de PEAK Final Ascent como contexto de uma rota variável', caption: 'Arte oficial da Steam como contexto da versão, não como prova de uma condição.' },
  },
  ko: {
    route: { src: '/media/peak-climb-ridge.webp', alt: '지정된 생물군계 경로에 다가가는 PEAK 등반 게임 화면', caption: '공식 Steam 스크린샷은 경로 맥락을 보여 줍니다. 배지 조건은 게임 안에서 확인하세요.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: '변화하는 경로의 버전 맥락을 보여 주는 공식 PEAK Final Ascent 아트', caption: '공식 Steam 아트는 버전 맥락을 위한 것이며 배지 조건의 증거가 아닙니다.' },
  },
  it: {
    route: { src: '/media/peak-climb-ridge.webp', alt: 'Schermata di PEAK con un arrampicatore vicino a un percorso di bioma', caption: 'Schermata ufficiale Steam come contesto del percorso; la condizione va verificata nel gioco.' },
    newMaps: { src: '/media/peak-final-ascent.webp', alt: 'Illustrazione ufficiale PEAK Final Ascent come contesto di un percorso variabile', caption: 'Illustrazione ufficiale Steam come contesto della versione, non come prova di una condizione.' },
  },
};

const copy = {
  en: {
    meta: { title: 'PEAK Badges Guide: In-Game Badges, Unlocks & Rewards', description: 'PEAK in-game badges guide: learn how badges work, what they unlock, and representative conditions grouped by route, survival, co-op, and gathering. Community-compiled; verify in-game.', schema: 'A PEAK in-game badges guide covering badge mechanics, representative unlock conditions, cosmetic rewards, community-source limits, and in-game verification.' },
    eyebrow: 'In-game progress desk · community snapshot 13 August 2026',
    h1: 'PEAK Badges Guide: How In-Game Badges Work & What They Unlock',
    intro: 'Short answer: PEAK badges are in-game progress markers awarded for specific actions. They appear on the Scout’s equipped sash, and each badge is tied to one or more cosmetic rewards. This guide shows representative conditions without presenting a community list as an official announcement.',
    answerLabel: 'The useful answer',
    answer: 'Open the pause menu and choose the Accolades screen to inspect badge progress. Unlocked badges show their names; locked entries are greyed out and use question marks. The 13 August 2026 PEAK Wiki snapshot records 64 badges, but the count and conditions can change. Except for Undead Encounter Badge, the source says badges can be earned on every difficulty including Tenderfoot; Custom Expeditions do not award badges.',
    mechanics: { eyebrow: 'How the system works', title: 'Track the action, the credit, and the reward', paragraphs: ['A badge may be granted immediately or after a run-end trigger; some counters span expeditions. Each card keeps the grant rule next to the condition.', 'Co-op credit is not uniform: some entries go to all living players, some to the player who performs the action, and some to every player regardless of alive or dead status.'], bullets: [['Immediate credit', 'A completed action can award the badge at once.'], ['Cumulative progress', 'Bouldering and Cooking count across expeditions.'], ['Help and feeding credit', 'When the source specifies it, feeding a teammate counts for the feeder.']] },
    listNote: 'This page shows representative entries only. For the complete list, open the PEAK pause menu → Accolades or consult the PEAK Wiki Badges page.',
    tocLabel: 'On this page',
    tocFaq: 'Badge FAQ',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.en,
    labels: commonLabels.en,
    sourceNote: 'Community-compiled from PEAK Wiki (wiki.gg), CC BY-SA 4.0, snapshot 13 August 2026. Verify the current description and result in-game on the Accolades screen.',
    patchNotes: { patch203Context: 'Map context: Patch 2.03.a added a Gloom/Citadel batch to the daily rotation.', patch204Context: 'Map context: Patch 2.04.a returned Caldera and The Kiln to the rotation and changed Kiln context.' },
    faq: { eyebrow: 'Quick answers', title: 'PEAK in-game badges FAQ', items: [['What are PEAK badges?', 'Badges are in-game progress markers awarded for specific actions. They appear on the Scout sash and connect to cosmetic rewards.'], ['Are PEAK badges the same as Steam achievements?', 'No. Steam achievements are platform records; badges are an in-game progress system. Similar actions may overlap, but neither proves the other.'], ['How many badges does PEAK have?', 'The 13 August 2026 community snapshot records 64 badges. The total may change, so use the current Accolades screen for the live count.'], ['Can Custom Expeditions earn badges?', 'No. The source says every badge except Undead Encounter Badge can be earned on all difficulties including Tenderfoot, but Custom Expeditions cannot award badges.'], ['Where do I view PEAK badges?', 'Open the pause menu and choose Accolades. Locked badges are greyed out and show question marks instead of names.']], achievementLink: 'Read the Steam achievement tracking guide' },
    source: { eyebrow: 'Sources and limits', title: 'Community list, in-game confirmation', body: 'The badge names, conditions, grant notes, and cosmetic names on this page are community-compiled from the PEAK Wiki snapshot. The source is not an official badge announcement. Use the Accolades screen in the current game as the final check, and use the official Steam store and patch posts only for version and route context.', wiki: 'PEAK Wiki Badges page', category: 'PEAK Wiki badge category', store: 'Official Steam store', patch203: 'Official Patch 2.03.a', patch204: 'Official Patch 2.04.a', license: 'CC BY-SA 4.0 license' },
    related: { home: 'Return to the progress tracker', achievements: 'Compare Steam achievements', items: 'Browse items for badge runs', updates: 'Read the update desk', map: 'Check map and route context' },
    bridge: { before: 'Steam achievements track platform records. For the in-game system, continue to the ', link: 'PEAK badges guide', after: '.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'A PEAK climber approaching a badge-related route challenge', caption: 'Official Steam screenshot used as gameplay context; the badge condition remains a community record to verify in-game.' },
    groupImages: groupImages.en,
  },
  zh: {
    meta: { title: 'PEAK 游戏内徽章攻略：玩法、解锁条件与奖励', description: 'PEAK 游戏内徽章攻略：了解徽章系统、Cosmetic 奖励和代表性解锁条件，按路线、生存、合作与采集制作整理。社区整理，需在游戏内核对。', schema: '一份 PEAK 游戏内徽章玩法指南，整理徽章机制、代表性解锁条件、Cosmetic 奖励、社区来源边界与游戏内核对方法。' },
    eyebrow: '游戏内进度资料 · 2026 年 8 月 13 日社区快照',
    h1: 'PEAK 游戏内徽章攻略：徽章怎么玩、能解锁什么',
    intro: '先说结论：PEAK 徽章是完成特定行为后获得的游戏内进度标记，会显示在 Scout 装备的绶带上，并与一个或多个 Cosmetic 奖励关联。本页只展示代表性条件，不把社区整理表当作官方发布。',
    answerLabel: '实用答案',
    answer: '打开暂停菜单中的 Accolades 屏幕即可查看徽章进度。已解锁徽章会显示名称，未解锁条目会灰显并显示问号。PEAK Wiki 2026 年 8 月 13 日快照记录为 64 个徽章，但总数和条件可能随版本变化。来源说明称，除 Undead Encounter Badge 外，所有徽章都可在包括 Tenderfoot 在内的全部难度获得；Custom Expeditions 不能获得徽章。',
    mechanics: { eyebrow: '徽章系统怎么运作', title: '条件、授予范围与奖励要一起看', paragraphs: ['徽章可能在行为完成时立即授予，也可能在终点营火等结算触发时授予；部分进度会跨远征累计。每张卡都把授予范围放在条件旁边。', '合作条目的计数归属并不相同：有些给所有存活玩家，有些只给完成动作的人，还有些无论存活或阵亡都给全队。'], bullets: [['即时结算', '完成动作后可能立即获得徽章。'], ['跨远征累计', 'Bouldering 与 Cooking 的进度会跨远征累计。'], ['帮助归属', '来源明确时，喂食队友的计数归喂食者。']] },
    listNote: '本页只展示代表性条目。完整列表请打开 PEAK 暂停菜单 → Accolades，或查看 PEAK Wiki 徽章页。',
    tocLabel: '本页内容',
    tocFaq: '徽章 FAQ',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.zh,
    labels: commonLabels.zh,
    sourceNote: '本页内容由 PEAK Wiki（wiki.gg）社区整理，采用 CC BY-SA 4.0，快照日期为 2026 年 8 月 13 日。请在当前游戏的 Accolades 屏幕核对描述与结果。',
    patchNotes: { patch203Context: '地图背景：2.03.a 补丁将 Gloom/Citadel 地图批次加入每日轮换。', patch204Context: '地图背景：2.04.a 补丁让 Caldera 与 The Kiln 回到轮换，并调整了 Kiln 背景。' },
    faq: { eyebrow: '快速回答', title: 'PEAK 游戏内徽章 FAQ', items: [['PEAK 徽章是什么？', '徽章是完成特定行为后获得的游戏内进度标记，会显示在 Scout 绶带上，并关联 Cosmetic 奖励。'], ['PEAK 徽章和 Steam 成就是一回事吗？', '不是。Steam 成就是平台记录，徽章是游戏内进度系统。两者可能对应相似行为，但不能互相证明。'], ['PEAK 一共有多少个徽章？', '2026 年 8 月 13 日的社区快照记录为 64 个。总数可能变化，应以当前游戏 Accolades 屏幕为准。'], ['Custom Expeditions 能获得徽章吗？', '不能。来源说明除 Undead Encounter Badge 外，其他徽章可在包括 Tenderfoot 在内的全部难度获得，但 Custom Expeditions 无法授予徽章。'], ['PEAK 徽章在哪里查看？', '打开暂停菜单并进入 Accolades。未解锁徽章会灰显，名称位置显示问号。']], achievementLink: '阅读 Steam 成就追踪攻略' },
    source: { eyebrow: '来源与边界', title: '社区整理，游戏内确认', body: '本页的徽章名、条件、授予说明和 Cosmetic 名称均来自 PEAK Wiki 快照的社区整理，并非官方徽章公告。当前游戏内的 Accolades 屏幕才是最终核对依据；官方 Steam 商店与补丁公告只用于版本和路线背景。', wiki: 'PEAK Wiki 徽章页', category: 'PEAK Wiki 徽章分类', store: 'Steam 官方商店', patch203: '官方 2.03.a 补丁', patch204: '官方 2.04.a 补丁', license: 'CC BY-SA 4.0 许可' },
    related: { home: '返回进度追踪区', achievements: '对照 Steam 成就', items: '查看徽章挑战道具', updates: '阅读版本更新', map: '查看地图与路线背景' },
    bridge: { before: 'Steam 成就记录平台进度；游戏内徽章玩法请继续阅读 ', link: 'PEAK 徽章攻略', after: '。' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'PEAK 玩家接近与徽章相关的路线挑战', caption: 'Steam 官方截图用于说明玩法背景；徽章条件仍应以游戏内结果核对。' },
    groupImages: groupImages.zh,
  },
  es: {
    meta: { title: 'Guía de insignias de PEAK: cómo funcionan y qué desbloquean', description: 'Guía de insignias de PEAK: sistema dentro del juego, recompensas cosméticas y condiciones representativas por ruta, supervivencia, cooperación y recolección. Fuente comunitaria; confirma en el juego.', schema: 'Guía de las insignias dentro del juego de PEAK con mecánicas, condiciones representativas, recompensas cosméticas y límites de la fuente comunitaria.' },
    eyebrow: 'Progreso dentro del juego · instantánea comunitaria del 13 de agosto de 2026',
    h1: 'Guía de insignias de PEAK: cómo funcionan y qué desbloquean',
    intro: 'En resumen, las insignias de PEAK son marcas de progreso dentro del juego que se conceden por acciones concretas. Aparecen en la banda equipada del Scout y se relacionan con una o varias recompensas cosméticas. Esta página muestra ejemplos representativos y no presenta una lista comunitaria como anuncio oficial.',
    answerLabel: 'La respuesta útil',
    answer: 'Abre el menú de pausa y entra en Accolades para consultar el progreso. Las insignias desbloqueadas muestran su nombre; las bloqueadas aparecen en gris y usan signos de interrogación. La instantánea de PEAK Wiki del 13 de agosto de 2026 registra 64 insignias, pero el total y las condiciones pueden cambiar. Según la fuente, salvo Undead Encounter Badge, todas pueden obtenerse en cualquier dificultad, incluida Tenderfoot; Custom Expeditions no concede insignias.',
    mechanics: { eyebrow: 'Cómo funciona el sistema', title: 'Mira la acción, quién recibe el crédito y la recompensa', paragraphs: ['Una insignia puede concederse al completar la acción o después de un activador al final de la expedición; algunos contadores se acumulan entre expediciones. Cada tarjeta mantiene la atribución junto a la condición.', 'El crédito cooperativo no es uniforme: algunas entradas se conceden a todos los jugadores vivos, otras a quien realiza la acción y otras a todos, estén vivos o muertos.'], bullets: [['Crédito inmediato', 'Una acción completada puede conceder la insignia al instante.'], ['Progreso acumulado', 'Bouldering y Cooking cuentan entre expediciones.'], ['Crédito por ayudar o alimentar', 'Cuando la fuente lo indica, alimentar a otro Scout cuenta para quien alimenta.']] },
    listNote: 'Esta página muestra solo entradas representativas. Para consultar la lista completa, abre el menú de pausa de PEAK → Accolades o consulta la página de insignias de PEAK Wiki.',
    tocLabel: 'En esta página',
    tocFaq: 'FAQ de insignias',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.es,
    labels: commonLabels.es,
    sourceNote: 'Recopilado por la comunidad desde PEAK Wiki (wiki.gg), con licencia CC BY-SA 4.0, instantánea del 13 de agosto de 2026. Confirma la descripción y el resultado actuales en la pantalla Accolades.',
    patchNotes: { patch203Context: 'Contexto de mapa: el parche 2.03.a añadió un grupo de mapas de Gloom/Citadel a la rotación diaria.', patch204Context: 'Contexto de mapa: el parche 2.04.a devolvió Caldera y The Kiln a la rotación y cambió el contexto de Kiln.' },
    faq: { eyebrow: 'Respuestas rápidas', title: 'FAQ de las insignias de PEAK', items: [['¿Qué son las insignias de PEAK?', 'Son marcas de progreso dentro del juego que se conceden por acciones concretas. Aparecen en la banda del Scout y se relacionan con recompensas cosméticas.'], ['¿Las insignias de PEAK son lo mismo que los logros de Steam?', 'No. Los logros de Steam son registros de la plataforma; las insignias son un sistema de progreso dentro del juego. Pueden coincidir en acciones, pero no se demuestran entre sí.'], ['¿Cuántas insignias tiene PEAK?', 'La instantánea comunitaria del 13 de agosto de 2026 registra 64. El total puede cambiar, así que usa la pantalla Accolades actual.'], ['¿Se pueden conseguir insignias en Custom Expeditions?', 'No. La fuente indica que todas salvo Undead Encounter Badge pueden obtenerse en cualquier dificultad, incluida Tenderfoot, pero Custom Expeditions no concede insignias.'], ['¿Dónde se ven las insignias de PEAK?', 'Abre el menú de pausa y entra en Accolades. Las insignias bloqueadas aparecen en gris y muestran signos de interrogación en lugar del nombre.']], achievementLink: 'Lee la guía para seguir los logros de Steam' },
    source: { eyebrow: 'Fuentes y límites', title: 'Lista comunitaria, confirmación en el juego', body: 'Los nombres, condiciones, notas de concesión y cosméticos de esta página proceden de la instantánea comunitaria de PEAK Wiki. No es un anuncio oficial de insignias. Usa Accolades en la versión actual como comprobación final; Steam oficial aporta solo el contexto de versión y ruta.', wiki: 'Página de insignias de PEAK Wiki', category: 'Categoría de insignias de PEAK Wiki', store: 'Tienda oficial de Steam', patch203: 'Parche oficial 2.03.a', patch204: 'Parche oficial 2.04.a', license: 'Licencia CC BY-SA 4.0' },
    related: { home: 'Volver al seguimiento del progreso', achievements: 'Comparar logros de Steam', items: 'Ver objetos para las rutas de insignias', updates: 'Leer las novedades', map: 'Ver el contexto de mapas y rutas' },
    bridge: { before: 'Los logros de Steam registran el progreso de la plataforma; para el sistema dentro del juego, consulta la ', link: 'guía de insignias de PEAK', after: '.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'Jugador de PEAK acercándose a un desafío de ruta relacionado con insignias', caption: 'Captura oficial de Steam como contexto de juego; la condición de la insignia debe confirmarse dentro del juego.' },
    groupImages: groupImages.es,
  },
  ja: {
    meta: { title: 'PEAK ゲーム内バッジ攻略：仕組み・解除条件・報酬', description: 'PEAKのゲーム内バッジ攻略。バッジの仕組み、Cosmetic報酬、ルート・生存・協力・採集の代表的な解除条件を整理。コミュニティ資料のためゲーム内で確認してください。', schema: 'PEAKのゲーム内バッジの仕組み、代表的な解除条件、Cosmetic報酬、コミュニティ資料の範囲とゲーム内確認方法をまとめた攻略。' },
    eyebrow: 'ゲーム内進行ガイド · 2026年8月13日コミュニティスナップショット',
    h1: 'PEAK ゲーム内バッジ攻略：仕組みと解除される報酬',
    intro: 'PEAKのバッジは、特定の行動を達成すると付与されるゲーム内の進行マーカーです。Scoutが装備するサッシュに表示され、1つ以上のCosmetic報酬と結び付きます。このページは代表例を扱い、コミュニティの一覧を公式発表として扱いません。',
    answerLabel: '先に答え',
    answer: '一時停止メニューからAccoladesを開くと進行を確認できます。解除済みは名前が表示され、未解除の項目は灰色で名前が「？」になります。2026年8月13日のPEAK Wikiスナップショットは64個としていますが、総数と条件はアップデートで変わる可能性があります。出典ではUndead Encounter Badgeを除きTenderfootを含む全難易度で取得でき、Custom Expeditionsでは取得できないとされています。',
    mechanics: { eyebrow: 'バッジの仕組み', title: '行動、付与対象、報酬をセットで確認', paragraphs: ['バッジは行動の完了時にすぐ付与される場合と、最後の焚き火などの終了トリガーで付与される場合があります。遠征をまたいで累積するカウンターもあります。各カードでは条件の横に付与範囲を示します。', '協力プレイでの付与対象は一律ではありません。生存者全員に付与されるもの、行動を実行したプレイヤーに付与されるもの、生死を問わず全員に付与されるものがあります。'], bullets: [['即時付与', '行動を完了するとすぐ解除される場合があります。'], ['遠征をまたぐ累積', 'BoulderingとCookingは複数の遠征で進行が累積します。'], ['手助け・食事の記録', '出典に記載がある場合、仲間に食べさせた側に加算されます。']] },
    listNote: 'このページは代表例のみを掲載しています。全リストはPEAKの一時停止メニュー → Accolades、またはPEAK Wikiのバッジページで確認してください。',
    tocLabel: 'このページの内容',
    tocFaq: 'バッジFAQ',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.ja,
    labels: commonLabels.ja,
    sourceNote: 'PEAK Wiki（wiki.gg）のコミュニティ整理を基にしています。CC BY-SA 4.0、スナップショットは2026年8月13日です。現在の説明と結果はゲーム内のAccoladesで確認してください。',
    patchNotes: { patch203Context: 'マップ背景：パッチ2.03.aでGloom/Citadelのマップ群がデイリーローテーションに追加された。', patch204Context: 'マップ背景：パッチ2.04.aでCalderaとThe Kilnがローテーションに戻り、Kilnの内容も変わった。' },
    faq: { eyebrow: 'よくある質問', title: 'PEAKゲーム内バッジ FAQ', items: [['PEAKのバッジとは？', '特定の行動を達成すると付与されるゲーム内の進行マーカーです。Scoutのサッシュに表示され、Cosmetic報酬と結び付きます。'], ['PEAKのバッジはSteam実績と同じですか？', '違います。Steam実績はプラットフォームの記録で、バッジはゲーム内の進行システムです。似た行動が条件になる場合はありますが、片方がもう片方の証明にはなりません。'], ['PEAKのバッジは何個ありますか？', '2026年8月13日のコミュニティスナップショットでは64個です。総数は変わる可能性があるため、現在のAccoladesで確認してください。'], ['Custom Expeditionsでバッジは取れますか？', '取れません。出典ではUndead Encounter Badge以外はTenderfootを含む全難易度で取得できますが、Custom Expeditionsは対象外です。'], ['PEAKのバッジはどこで見ますか？', '一時停止メニューからAccoladesを開きます。未解除のバッジは灰色で、名前の代わりに「？」が表示されます。']], achievementLink: 'Steam実績の追跡ガイドを読む' },
    source: { eyebrow: '出典と範囲', title: 'コミュニティ一覧をゲーム内で確認', body: 'このページのバッジ名、条件、付与メモ、Cosmetic名はPEAK Wikiのスナップショットに基づくコミュニティ整理です。公式のバッジ発表ではありません。現在のゲーム内Accoladesを最終確認に使い、Steam公式ページとパッチ記事はバージョンやルートの背景として参照してください。', wiki: 'PEAK Wikiバッジページ', category: 'PEAK Wikiバッジカテゴリ', store: 'Steam公式ストア', patch203: '公式パッチ2.03.a', patch204: '公式パッチ2.04.a', license: 'CC BY-SA 4.0ライセンス' },
    related: { home: '進行トラッカーに戻る', achievements: 'Steam実績と比較する', items: 'バッジ挑戦用のアイテムを見る', updates: 'アップデートを見る', map: 'マップとルートの背景を見る' },
    bridge: { before: 'Steam実績はプラットフォームの記録です。ゲーム内システムは', link: 'PEAKバッジ攻略', after: 'で確認できます。' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'バッジに関係するルートチャレンジへ向かうPEAKの登山者', caption: 'Steam公式スクリーンショットはゲームの背景用です。バッジ条件はゲーム内で確認してください。' },
    groupImages: groupImages.ja,
  },
  fr: {
    meta: { title: 'Guide des badges de PEAK : fonctionnement et récompenses', description: 'Guide des badges de PEAK : fonctionnement, récompenses cosmétiques et conditions représentatives par route, survie, coopération et collecte. Source communautaire à vérifier en jeu.', schema: 'Guide des badges de PEAK dans le jeu, avec mécanismes, conditions représentatives, récompenses cosmétiques et limites de la source communautaire.' },
    eyebrow: 'Progression en jeu · instantané communautaire du 13 août 2026',
    h1: 'Guide des badges de PEAK : comment ils fonctionnent et ce qu ils débloquent',
    intro: 'En bref, les badges de PEAK sont des marqueurs de progression en jeu attribués après certaines actions. Ils apparaissent sur la sash équipée du Scout et sont associés à une ou plusieurs récompenses cosmétiques. Cette page présente des exemples et ne transforme pas une liste communautaire en annonce officielle.',
    answerLabel: 'La réponse utile',
    answer: 'Ouvrez le menu pause puis l écran Accolades pour consulter la progression. Les badges débloqués affichent leur nom ; les badges verrouillés sont grisés et remplacés par des points d interrogation. L instantané PEAK Wiki du 13 août 2026 en compte 64, mais le total et les conditions peuvent changer. D après la source, tous les badges sauf Undead Encounter Badge sont accessibles dans toutes les difficultés, Tenderfoot compris ; Custom Expeditions ne donne pas de badge.',
    mechanics: { eyebrow: 'Fonctionnement du système', title: 'Suivre l action, le bénéficiaire et la récompense', paragraphs: ['Un badge peut être attribué dès que l action est terminée ou après un déclencheur de fin de partie ; certains compteurs se cumulent entre les expéditions. Chaque fiche place la règle d attribution à côté de la condition.', 'L attribution en coopération varie : certaines entrées concernent tous les joueurs vivants, d autres la personne qui réalise l action, et d autres tous les joueurs, vivants ou morts.'], bullets: [['Attribution immédiate', 'Une action terminée peut débloquer le badge immédiatement.'], ['Progression cumulative', 'Bouldering et Cooking se cumulent entre les expéditions.'], ['Crédit d aide et de nourriture', 'Lorsque la source le précise, nourrir un autre Scout compte pour celui qui le nourrit.']] },
    listNote: 'Cette page présente uniquement des entrées représentatives. Pour la liste complète, ouvrez le menu pause de PEAK → Accolades ou consultez la page des badges de PEAK Wiki.',
    tocLabel: 'Sur cette page',
    tocFaq: 'FAQ des badges',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.fr,
    labels: commonLabels.fr,
    sourceNote: 'Compilation communautaire provenant de PEAK Wiki (wiki.gg), sous licence CC BY-SA 4.0, instantané du 13 août 2026. Vérifiez la description et le résultat actuels dans Accolades.',
    patchNotes: { patch203Context: 'Contexte de carte : le patch 2.03.a a ajouté un groupe de cartes Gloom/Citadel à la rotation quotidienne.', patch204Context: 'Contexte de carte : le patch 2.04.a a remis Caldera et The Kiln dans la rotation et a modifié le contexte de Kiln.' },
    faq: { eyebrow: 'Réponses rapides', title: 'FAQ des badges de PEAK', items: [['Que sont les badges de PEAK ?', 'Ce sont des marqueurs de progression en jeu attribués après certaines actions. Ils apparaissent sur la sash du Scout et sont associés à des récompenses cosmétiques.'], ['Les badges de PEAK sont-ils les mêmes que les succès Steam ?', 'Non. Les succès Steam sont des registres de plateforme ; les badges sont un système de progression dans le jeu. Les actions peuvent se ressembler, mais l un ne prouve pas l autre.'], ['Combien de badges PEAK possède-t-il ?', 'L instantané communautaire du 13 août 2026 en compte 64. Le total peut évoluer : vérifiez Accolades dans la version actuelle.'], ['Les Custom Expeditions donnent-elles des badges ?', 'Non. La source indique que tous les badges sauf Undead Encounter Badge sont accessibles dans toutes les difficultés, Tenderfoot compris, mais Custom Expeditions ne donnent pas de badge.'], ['Où voir les badges de PEAK ?', 'Ouvrez le menu pause puis Accolades. Les badges verrouillés sont grisés et affichent des points d interrogation à la place du nom.']], achievementLink: 'Lire le guide de suivi des succès Steam' },
    source: { eyebrow: 'Sources et limites', title: 'Liste communautaire, vérification en jeu', body: 'Les noms, conditions, notes d attribution et noms de cosmétiques viennent de l instantané communautaire de PEAK Wiki. Il ne s agit pas d une annonce officielle. Utilisez Accolades dans le jeu actuel comme vérification finale ; les pages Steam officielles donnent seulement le contexte de version et de route.', wiki: 'Page des badges de PEAK Wiki', category: 'Catégorie des badges PEAK Wiki', store: 'Boutique Steam officielle', patch203: 'Patch officiel 2.03.a', patch204: 'Patch officiel 2.04.a', license: 'Licence CC BY-SA 4.0' },
    related: { home: 'Retour au suivi de progression', achievements: 'Comparer les succès Steam', items: 'Voir les objets utiles aux badges', updates: 'Lire les actualités', map: 'Voir le contexte des cartes et routes' },
    bridge: { before: 'Les succès Steam suivent les records de plateforme ; pour le système en jeu, consultez le ', link: 'guide des badges de PEAK', after: '.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'Grimpeur de PEAK approchant un défi de route lié aux badges', caption: 'Capture officielle Steam comme contexte de jeu ; la condition du badge doit être vérifiée en jeu.' },
    groupImages: groupImages.fr,
  },
  de: {
    meta: { title: 'PEAK-Abzeichen-Guide: In-Game-Abzeichen und Belohnungen', description: 'PEAK-Abzeichen-Guide: Abzeichen im Spiel, kosmetische Belohnungen und beispielhafte Bedingungen für Route, Überleben, Koop und Sammeln. Community-Quelle, im Spiel prüfen.', schema: 'Ein Guide zu PEAK-Abzeichen im Spiel mit Mechanik, beispielhaften Bedingungen, kosmetischen Belohnungen und Grenzen der Community-Quelle.' },
    eyebrow: 'In-Game-Fortschritt · Community-Stand 13.08.2026',
    h1: 'PEAK-Abzeichen-Guide: Wie In-Game-Abzeichen funktionieren und was sie freischalten',
    intro: 'Kurz gesagt: PEAK-Abzeichen sind Fortschrittsmarkierungen im Spiel, die für bestimmte Aktionen vergeben werden. Sie erscheinen auf der ausgerüsteten Sash des Scouts und sind mit einer oder mehreren kosmetischen Belohnungen verbunden. Dieser Guide zeigt Beispiele und stellt die Community-Liste nicht als offizielle Ankündigung dar.',
    answerLabel: 'Die nützliche Antwort',
    answer: 'Öffne das Pausenmenü und den Accolades-Bildschirm, um den Fortschritt zu prüfen. Freigeschaltete Abzeichen zeigen ihren Namen; gesperrte Einträge sind grau und zeigen Fragezeichen. Der PEAK-Wiki-Stand vom 13.08.2026 nennt 64 Abzeichen, aber Anzahl und Bedingungen können sich ändern. Laut Quelle sind außer Undead Encounter Badge alle Abzeichen auf allen Schwierigkeitsgraden einschließlich Tenderfoot möglich; Custom Expeditions vergeben keine Abzeichen.',
    mechanics: { eyebrow: 'So funktioniert das System', title: 'Aktion, Vergabe und Belohnung zusammen lesen', paragraphs: ['Ein Abzeichen kann sofort nach der Aktion oder durch einen Auslöser am Ende der Expedition vergeben werden; manche Zähler werden über Expeditionen hinweg gesammelt. Jede Karte nennt die Vergabe direkt neben der Bedingung.', 'Die Koop-Vergabe ist nicht einheitlich: Manche Einträge gelten für alle lebenden Spieler, manche für die Person, die die Aktion ausführt, und manche für alle Spieler unabhängig davon, ob sie leben oder tot sind.'], bullets: [['Sofortige Vergabe', 'Eine abgeschlossene Aktion kann das Abzeichen direkt geben.'], ['Kumulativer Fortschritt', 'Bouldering und Cooking zählen über mehrere Expeditionen hinweg.'], ['Hilfe- und Fütterungscredit', 'Wenn die Quelle es sagt, zählt das Füttern eines anderen Scouts für die fütternde Person.']] },
    listNote: 'Diese Seite zeigt nur repräsentative Einträge. Die vollständige Liste findest du im PEAK-Pausenmenü → Accolades oder auf der Abzeichenseite der PEAK Wiki.',
    tocLabel: 'Auf dieser Seite',
    tocFaq: 'Abzeichen-FAQ',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.de,
    labels: commonLabels.de,
    sourceNote: 'Aus der Community-Zusammenstellung von PEAK Wiki (wiki.gg), CC BY-SA 4.0, Stand 13.08.2026. Prüfe aktuelle Beschreibung und Ergebnis im Accolades-Bildschirm.',
    patchNotes: { patch203Context: 'Kartenkontext: Patch 2.03.a fügte einen Gloom/Citadel-Kartenblock zur täglichen Rotation hinzu.', patch204Context: 'Kartenkontext: Patch 2.04.a brachte Caldera und The Kiln zurück in die Rotation und änderte den Kiln-Kontext.' },
    faq: { eyebrow: 'Schnelle Antworten', title: 'PEAK-Abzeichen-FAQ', items: [['Was sind PEAK-Abzeichen?', 'Abzeichen sind Fortschrittsmarkierungen im Spiel für bestimmte Aktionen. Sie erscheinen auf der Scout-Sash und sind mit kosmetischen Belohnungen verbunden.'], ['Sind PEAK-Abzeichen dasselbe wie Steam-Erfolge?', 'Nein. Steam-Erfolge sind Plattformaufzeichnungen; Abzeichen sind ein Fortschrittssystem im Spiel. Aktionen können sich überschneiden, aber keines beweist das andere.'], ['Wie viele Abzeichen hat PEAK?', 'Der Community-Stand vom 13.08.2026 nennt 64. Die Zahl kann sich ändern; prüfe deshalb den aktuellen Accolades-Bildschirm.'], ['Geben Custom Expeditions Abzeichen?', 'Nein. Laut Quelle sind alle Abzeichen außer Undead Encounter Badge auf allen Schwierigkeitsgraden einschließlich Tenderfoot möglich, aber Custom Expeditions vergeben keine Abzeichen.'], ['Wo sehe ich PEAK-Abzeichen?', 'Öffne das Pausenmenü und Accolades. Gesperrte Abzeichen sind grau und zeigen statt ihres Namens Fragezeichen.']], achievementLink: 'Steam-Erfolge-Tracking-Guide lesen' },
    source: { eyebrow: 'Quellen und Grenzen', title: 'Community-Liste im Spiel prüfen', body: 'Namen, Bedingungen, Vergabehinweise und Cosmetic-Namen stammen aus dem Community-Stand der PEAK Wiki. Das ist keine offizielle Abzeichen-Ankündigung. Nutze Accolades im aktuellen Spiel als letzte Prüfung; offizielle Steam-Seiten liefern den Versions- und Routen-Kontext.', wiki: 'PEAK-Wiki-Abzeichenseite', category: 'PEAK-Wiki-Abzeichenkategorie', store: 'Offizieller Steam-Store', patch203: 'Offizieller Patch 2.03.a', patch204: 'Offizieller Patch 2.04.a', license: 'CC-BY-SA-4.0-Lizenz' },
    related: { home: 'Zum Fortschritts-Tracker', achievements: 'Steam-Erfolge vergleichen', items: 'Passende Gegenstände ansehen', updates: 'Update-Desk lesen', map: 'Karten- und Routen-Kontext prüfen' },
    bridge: { before: 'Steam-Erfolge verfolgen Plattformaufzeichnungen. Für das System im Spiel geht es weiter zum ', link: 'PEAK-Abzeichen-Guide', after: '.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'PEAK-Kletterer auf dem Weg zu einer abzeichenbezogenen Routenherausforderung', caption: 'Offizieller Steam-Screenshot als Spielkontext; die Abzeichenbedingung muss im Spiel geprüft werden.' },
    groupImages: groupImages.de,
  },
  pt: {
    meta: { title: 'Guia de distintivos de PEAK: funcionamento e recompensas', description: 'Guia dos distintivos de PEAK: sistema dentro do jogo, recompensas cosméticas e condições representativas por rota, sobrevivência, cooperação e coleta. Fonte comunitária; confirme no jogo.', schema: 'Guia dos distintivos de PEAK dentro do jogo, com mecânicas, condições representativas, recompensas cosméticas e limites da fonte comunitária.' },
    eyebrow: 'Progresso dentro do jogo · instantâneo da comunidade de 13 de agosto de 2026',
    h1: 'Guia de distintivos de PEAK: como funcionam e o que desbloqueiam',
    intro: 'Em resumo, os distintivos de PEAK são marcadores de progresso dentro do jogo, concedidos por ações específicas. Eles aparecem na sash equipada do Scout e se relacionam a uma ou mais recompensas cosméticas. Esta página mostra exemplos e não trata uma lista da comunidade como anúncio oficial.',
    answerLabel: 'A resposta útil',
    answer: 'Abra o menu de pausa e escolha Accolades para consultar o progresso. Distintivos desbloqueados mostram o nome; entradas bloqueadas ficam cinzas e usam pontos de interrogação. O instantâneo da PEAK Wiki de 13 de agosto de 2026 registra 64 distintivos, mas o total e as condições podem mudar. A fonte diz que, exceto Undead Encounter Badge, todos podem ser obtidos em qualquer dificuldade, incluindo Tenderfoot; Custom Expeditions não concedem distintivos.',
    mechanics: { eyebrow: 'Como o sistema funciona', title: 'Leia a ação, quem recebe o crédito e a recompensa', paragraphs: ['Um distintivo pode ser concedido imediatamente ou após um gatilho no fim da expedição; alguns contadores acumulam entre expedições. Cada cartão mantém a regra de concessão junto da condição.', 'O crédito na cooperação varia: alguns itens são concedidos a todos os jogadores vivos, outros a quem executa a ação e outros a todos, vivos ou mortos.'], bullets: [['Crédito imediato', 'Uma ação concluída pode conceder o distintivo na hora.'], ['Progresso cumulativo', 'Bouldering e Cooking contam ao longo de várias expedições.'], ['Crédito por ajuda e alimentação', 'Quando a fonte especifica, alimentar outro Scout conta para quem alimenta.']] },
    listNote: 'Esta página mostra apenas entradas representativas. Para a lista completa, abra o menu de pausa do PEAK → Accolades ou consulte a página de distintivos da PEAK Wiki.',
    tocLabel: 'Nesta página',
    tocFaq: 'FAQ de distintivos',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.pt,
    labels: commonLabels.pt,
    sourceNote: 'Compilado pela comunidade a partir da PEAK Wiki (wiki.gg), sob CC BY-SA 4.0, instantâneo de 13 de agosto de 2026. Confirme a descrição e o resultado atuais na tela Accolades.',
    patchNotes: { patch203Context: 'Contexto de mapa: o patch 2.03.a adicionou um conjunto de mapas de Gloom/Citadel à rotação diária.', patch204Context: 'Contexto de mapa: o patch 2.04.a trouxe Caldera e The Kiln de volta à rotação e mudou o contexto de Kiln.' },
    faq: { eyebrow: 'Respostas rápidas', title: 'FAQ dos distintivos de PEAK', items: [['O que são os distintivos de PEAK?', 'São marcadores de progresso dentro do jogo, concedidos por ações específicas. Aparecem na sash do Scout e se relacionam a recompensas cosméticas.'], ['Os distintivos de PEAK são iguais às conquistas Steam?', 'Não. Conquistas Steam são registros da plataforma; distintivos são um sistema de progresso dentro do jogo. As ações podem se parecer, mas um não prova o outro.'], ['Quantos distintivos PEAK tem?', 'O instantâneo comunitário de 13 de agosto de 2026 registra 64. O total pode mudar; confira a tela Accolades atual.'], ['Custom Expeditions dão distintivos?', 'Não. A fonte diz que todos, exceto Undead Encounter Badge, podem ser obtidos em todas as dificuldades, incluindo Tenderfoot, mas Custom Expeditions não concedem distintivos.'], ['Onde vejo os distintivos de PEAK?', 'Abra o menu de pausa e entre em Accolades. Distintivos bloqueados ficam cinzas e mostram pontos de interrogação no lugar do nome.']], achievementLink: 'Leia o guia de acompanhamento das conquistas Steam' },
    source: { eyebrow: 'Fontes e limites', title: 'Lista comunitária, confirmação no jogo', body: 'Os nomes, condições, notas de concessão e nomes de cosméticos desta página vêm do instantâneo comunitário da PEAK Wiki. Não é um anúncio oficial de distintivos. Use Accolades na versão atual como confirmação final; as páginas oficiais da Steam fornecem apenas o contexto de versão e rota.', wiki: 'Página de distintivos da PEAK Wiki', category: 'Categoria de distintivos da PEAK Wiki', store: 'Loja oficial da Steam', patch203: 'Patch oficial 2.03.a', patch204: 'Patch oficial 2.04.a', license: 'Licença CC BY-SA 4.0' },
    related: { home: 'Voltar ao acompanhamento do progresso', achievements: 'Comparar conquistas Steam', items: 'Ver itens úteis para distintivos', updates: 'Ler o painel de atualizações', map: 'Ver o contexto de mapas e rotas' },
    bridge: { before: 'As conquistas Steam registram o progresso da plataforma; para o sistema dentro do jogo, leia o ', link: 'guia de distintivos de PEAK', after: '.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'Jogador de PEAK se aproximando de um desafio de rota ligado a distintivos', caption: 'Captura oficial da Steam como contexto de jogo; confirme a condição do distintivo dentro do jogo.' },
    groupImages: groupImages.pt,
  },
  ko: {
    meta: { title: 'PEAK 게임 내 배지 가이드: 작동 방식과 보상', description: 'PEAK 게임 내 배지 가이드: 배지 시스템, Cosmetic 보상과 경로·생존·협동·채집별 대표 잠금 해제 조건을 정리합니다. 커뮤니티 자료이므로 게임 안에서 확인하세요.', schema: 'PEAK 게임 내 배지의 작동 방식, 대표 잠금 해제 조건, Cosmetic 보상, 커뮤니티 출처의 범위와 게임 내 확인 방법을 설명하는 가이드.' },
    eyebrow: '게임 내 진행 가이드 · 2026년 8월 13일 커뮤니티 스냅샷',
    h1: 'PEAK 게임 내 배지 가이드: 작동 방식과 해제되는 보상',
    intro: 'PEAK 배지는 특정 행동을 완료하면 받는 게임 내 진행 표시입니다. Scout이 장착한 새시에 표시되며 하나 이상의 Cosmetic 보상과 연결됩니다. 이 페이지는 대표 조건을 다루며 커뮤니티 목록을 공식 발표처럼 제시하지 않습니다.',
    answerLabel: '핵심 답변',
    answer: '일시 정지 메뉴에서 Accolades 화면을 열어 배지 진행을 확인하세요. 해제된 배지는 이름이 보이고, 잠긴 항목은 회색으로 표시되며 이름 대신 물음표가 나타납니다. 2026년 8월 13일 PEAK Wiki 스냅샷은 배지 64개를 기록하지만 개수와 조건은 업데이트로 바뀔 수 있습니다. 출처에 따르면 Undead Encounter Badge를 제외한 모든 배지는 Tenderfoot를 포함한 모든 난이도에서 얻을 수 있으며 Custom Expeditions에서는 배지를 얻을 수 없습니다.',
    mechanics: { eyebrow: '배지 시스템 작동 방식', title: '행동, 적용 대상과 보상을 함께 확인하세요', paragraphs: ['배지는 행동을 완료하는 즉시 적용되거나 원정 종료 시점의 조건이 충족될 때 적용될 수 있습니다. 여러 원정에 걸쳐 누적되는 카운터도 있습니다. 각 카드에서 조건과 적용 대상을 함께 확인하세요.', '협동 플레이의 적용 대상은 모두 같지 않습니다. 살아 있는 모든 플레이어에게 적용되는 항목, 행동을 수행한 플레이어에게만 적용되는 항목, 생사와 관계없이 모든 플레이어에게 적용되는 항목이 있습니다.'], bullets: [['즉시 적용', '행동을 완료하면 바로 배지를 받을 수 있습니다.'], ['여러 원정 누적', 'Bouldering과 Cooking은 여러 원정에 걸쳐 진행도가 누적됩니다.'], ['도움과 먹이 주기', '출처에 명시된 경우 동료에게 먹이를 준 플레이어의 진행으로 계산됩니다.']] },
    listNote: '이 페이지는 대표 항목만 보여 줍니다. 전체 목록은 PEAK 일시 정지 메뉴 → Accolades 또는 PEAK Wiki 배지 페이지에서 확인하세요.',
    tocLabel: '이 페이지의 내용',
    tocFaq: '배지 FAQ',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.ko,
    labels: commonLabels.ko,
    sourceNote: 'PEAK Wiki (wiki.gg) 커뮤니티 정리를 바탕으로 하며 CC BY-SA 4.0을 적용합니다. 스냅샷은 2026년 8월 13일입니다. 현재 설명과 결과는 게임 안의 Accolades 화면에서 확인하세요.',
    patchNotes: { patch203Context: '맵 배경: 2.03.a 패치가 Gloom/Citadel 맵 묶음을 일일 로테이션에 추가했습니다.', patch204Context: '맵 배경: 2.04.a 패치가 Caldera와 The Kiln을 로테이션에 되돌리고 Kiln 맥락을 변경했습니다.' },
    faq: { eyebrow: '빠른 답변', title: 'PEAK 게임 내 배지 FAQ', items: [['PEAK 배지는 무엇인가요?', '특정 행동을 완료하면 받는 게임 내 진행 표시입니다. Scout의 새시에 표시되고 Cosmetic 보상과 연결됩니다.'], ['PEAK 배지는 Steam 도전 과제와 같은가요?', '아닙니다. Steam 도전 과제는 플랫폼 기록이고 배지는 게임 내 진행 시스템입니다. 행동이 비슷할 수 있지만 서로를 증명하지는 않습니다.'], ['PEAK 배지는 몇 개인가요?', '2026년 8월 13일 커뮤니티 스냅샷은 64개를 기록합니다. 개수는 바뀔 수 있으므로 현재 Accolades 화면을 확인하세요.'], ['Custom Expeditions에서도 배지를 얻을 수 있나요?', '아닙니다. 출처는 Undead Encounter Badge를 제외한 배지가 Tenderfoot를 포함한 모든 난이도에서 가능하다고 하지만 Custom Expeditions에서는 배지를 받을 수 없다고 설명합니다.'], ['PEAK 배지는 어디서 보나요?', '일시 정지 메뉴에서 Accolades를 여세요. 잠긴 배지는 회색으로 표시되고 이름 대신 물음표가 보입니다.']], achievementLink: 'Steam 도전 과제 추적 가이드 읽기' },
    source: { eyebrow: '출처와 범위', title: '커뮤니티 목록을 게임 안에서 확인', body: '이 페이지의 배지 이름, 조건, 적용 메모와 Cosmetic 이름은 PEAK Wiki 스냅샷의 커뮤니티 정리에서 가져왔습니다. 공식 배지 발표가 아닙니다. 현재 게임의 Accolades를 최종 확인으로 사용하고, 공식 Steam 페이지는 버전과 경로 배경을 확인하는 데만 사용하세요.', wiki: 'PEAK Wiki 배지 페이지', category: 'PEAK Wiki 배지 분류', store: '공식 Steam 상점', patch203: '공식 2.03.a 패치', patch204: '공식 2.04.a 패치', license: 'CC BY-SA 4.0 라이선스' },
    related: { home: '진행 추적기로 돌아가기', achievements: 'Steam 도전 과제 비교하기', items: '배지 도전에 쓸 아이템 보기', updates: '업데이트 데스크 읽기', map: '맵과 경로 배경 보기' },
    bridge: { before: 'Steam 도전 과제는 플랫폼 기록입니다. 게임 내 시스템은 ', link: 'PEAK 배지 가이드', after: '에서 확인하세요.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: '배지 관련 경로 도전에 다가가는 PEAK 등반가', caption: '공식 Steam 스크린샷은 게임 맥락을 보여 줍니다. 배지 조건은 게임 안에서 확인하세요.' },
    groupImages: groupImages.ko,
  },
  it: {
    meta: { title: 'Guida ai badge di PEAK: funzionamento e ricompense', description: 'Guida ai badge di PEAK: sistema nel gioco, ricompense cosmetiche e condizioni rappresentative per percorso, sopravvivenza, cooperazione e raccolta. Fonte comunitaria: verifica nel gioco.', schema: 'Guida ai badge di PEAK nel gioco con meccaniche, condizioni rappresentative, ricompense cosmetiche, limiti della fonte comunitaria e verifica in gioco.' },
    eyebrow: 'Progressi nel gioco · snapshot della community del 13 agosto 2026',
    h1: 'Guida ai badge di PEAK: come funzionano e cosa sbloccano',
    intro: 'In breve, i badge di PEAK sono indicatori di progresso nel gioco assegnati per azioni specifiche. Appaiono sulla sash equipaggiata dello Scout e sono collegati a una o più ricompense cosmetiche. Questa pagina mostra esempi rappresentativi e non presenta un elenco comunitario come annuncio ufficiale.',
    answerLabel: 'La risposta utile',
    answer: 'Apri il menu di pausa e la schermata Accolades per controllare i progressi. I badge sbloccati mostrano il nome; quelli bloccati sono grigi e usano punti interrogativi. Lo snapshot di PEAK Wiki del 13 agosto 2026 ne registra 64, ma quantità e condizioni possono cambiare. Secondo la fonte, tutti i badge tranne Undead Encounter Badge sono ottenibili a ogni difficoltà, inclusa Tenderfoot; Custom Expeditions non assegna badge.',
    mechanics: { eyebrow: 'Come funziona il sistema', title: 'Leggi insieme azione, beneficiario e ricompensa', paragraphs: ['Un badge può essere assegnato subito dopo l azione o dopo un evento di fine spedizione; alcuni contatori si accumulano tra le spedizioni. Ogni scheda mantiene la regola di assegnazione accanto alla condizione.', 'L assegnazione in cooperativa non è uniforme: alcune voci valgono per tutti i giocatori vivi, altre per chi esegue l azione e altre per tutti, vivi o morti.'], bullets: [['Assegnazione immediata', 'Un azione completata può sbloccare subito il badge.'], ['Progresso cumulativo', 'Bouldering e Cooking contano tra più spedizioni.'], ['Credito per aiuto e cibo', 'Quando la fonte lo specifica, nutrire un altro Scout conta per chi lo nutre.']] },
    listNote: 'Questa pagina mostra solo voci rappresentative. Per l elenco completo, apri il menu di pausa di PEAK → Accolades o consulta la pagina dei badge di PEAK Wiki.',
    tocLabel: 'In questa pagina',
    tocFaq: 'FAQ sui badge',
    groupOrder: ['route', 'survival', 'coop', 'crafting', 'newMaps'],
    groups: groupCopy.it,
    labels: commonLabels.it,
    sourceNote: 'Compilato dalla community a partire da PEAK Wiki (wiki.gg), con licenza CC BY-SA 4.0, snapshot del 13 agosto 2026. Verifica descrizione e risultato attuali nella schermata Accolades.',
    patchNotes: { patch203Context: 'Contesto della mappa: la patch 2.03.a ha aggiunto un gruppo di mappe Gloom/Citadel alla rotazione giornaliera.', patch204Context: 'Contesto della mappa: la patch 2.04.a ha riportato Caldera e The Kiln nella rotazione e ha cambiato il contesto di Kiln.' },
    faq: { eyebrow: 'Risposte rapide', title: 'FAQ sui badge di PEAK', items: [['Cosa sono i badge di PEAK?', 'Sono indicatori di progresso nel gioco assegnati per azioni specifiche. Appaiono sulla sash dello Scout e sono collegati a ricompense cosmetiche.'], ['I badge di PEAK sono uguali agli obiettivi Steam?', 'No. Gli obiettivi Steam sono registri della piattaforma; i badge sono un sistema di progresso nel gioco. Le azioni possono coincidere, ma uno non prova l altro.'], ['Quanti badge ha PEAK?', 'Lo snapshot comunitario del 13 agosto 2026 ne registra 64. Il totale può cambiare, quindi controlla la schermata Accolades attuale.'], ['Le Custom Expeditions danno badge?', 'No. La fonte indica che tutti tranne Undead Encounter Badge sono ottenibili a ogni difficoltà, inclusa Tenderfoot, ma Custom Expeditions non assegnano badge.'], ['Dove si vedono i badge di PEAK?', 'Apri il menu di pausa e Accolades. I badge bloccati sono grigi e mostrano punti interrogativi al posto del nome.']], achievementLink: 'Leggi la guida al monitoraggio degli obiettivi Steam' },
    source: { eyebrow: 'Fonti e limiti', title: 'Elenco comunitario, verifica nel gioco', body: 'Nomi, condizioni, note di assegnazione e nomi dei cosmetici provengono dallo snapshot comunitario di PEAK Wiki. Non è un annuncio ufficiale dei badge. Usa Accolades nella versione attuale come controllo finale; le pagine Steam ufficiali forniscono solo il contesto di versione e percorso.', wiki: 'Pagina dei badge di PEAK Wiki', category: 'Categoria badge di PEAK Wiki', store: 'Store ufficiale Steam', patch203: 'Patch ufficiale 2.03.a', patch204: 'Patch ufficiale 2.04.a', license: 'Licenza CC BY-SA 4.0' },
    related: { home: 'Torna al monitoraggio dei progressi', achievements: 'Confronta gli obiettivi Steam', items: 'Vedi gli oggetti utili ai badge', updates: 'Leggi gli aggiornamenti', map: 'Vedi il contesto di mappe e percorsi' },
    bridge: { before: 'Gli obiettivi Steam registrano i progressi della piattaforma; per il sistema nel gioco leggi la ', link: 'guida ai badge di PEAK', after: '.' },
    heroImage: { src: '/media/peak-climb-ridge.webp', alt: 'Scalatore di PEAK vicino a una sfida di percorso legata ai badge', caption: 'Schermata ufficiale Steam come contesto di gioco; la condizione del badge va verificata nel gioco.' },
    groupImages: groupImages.it,
  },
};

for (const locale of localeOrder) {
  if (!copy[locale]) throw new Error(`Missing badge guide copy: ${locale}`);
  if (!grantCopy[locale]) throw new Error(`Missing badge grant copy: ${locale}`);
  if (!copy[locale].groupOrder?.every((group) => copy[locale].groups[group])) throw new Error(`Missing badge guide group copy: ${locale}`);
  if (!copy[locale].mechanics?.paragraphs?.length || !copy[locale].mechanics?.bullets?.length) throw new Error(`Missing badge guide mechanics copy: ${locale}`);
  if (!copy[locale].listNote || !copy[locale].related?.items) throw new Error(`Missing badge guide navigation copy: ${locale}`);
  if (!copy[locale].groupImages?.route || !copy[locale].groupImages?.newMaps) throw new Error(`Missing badge guide group image: ${locale}`);
}

for (const entry of badgeGuideEntries) {
  if (!entry.name || !entry.grantKey || !entry.reward || !localeOrder.every((locale) => entry.condition?.[locale])) throw new Error(`Incomplete badge guide entry: ${entry.name ?? 'unknown'}`);
}

export const badgeGuideCopy = copy;
export const badgeGrantCopy = grantCopy;
export const badgeCardLabels = commonLabels;
